### ISSUE TITLE
Unable to see Plex Media Server Logs in Tautulli (Plexpy)

### ISSUE THREAD

**Issue by Eric-sson** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#102]
The error that I get: Unable to open Plex Log file. [Errno 2] No such file or directory: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log'

I have checked and the file is available on the location. Any ideas?

**Comment by Admin9705** [comment]
Will require some research. Not something i even paid attention to :D Will check into it :D

**Comment by Admin9705** [comment]
@Eric-sson apolgizes still haven't seen much into this. too many things going on :D
