### ISSUE TITLE
Option to host Plex Metadata on Gdrive?

### ISSUE THREAD

**Issue by predator2003** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#105]
Hello is it possible to move the local metadata folder to a remote gdrive mount?

**Comment by designgears** [comment]
I think having an option to backup the appdata to gdrive would be nice, along with an option to restore the data if it is found and doesn't exist on local.

**Comment by Admin9705** [comment]
@designgears it actually does that :D; it doesn't exist on local. but could do a menu thing to offer local :D

**Comment by designgears** [comment]
Oh hey, look at that, backup and restore in the menu, I must be blind :D

**Comment by Admin9705** [comment]
@designgears lol :D
