### ISSUE TITLE
Plex reading issue creating remote access

### ISSUE THREAD

**Issue by Budman17r** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#110]
Recent update I think it has to do with advertise IP and network system host.

**Comment by Budman17r** [comment]
So when I commented out advertise
```
#      ADVERTISE_IP: "http://{{local_ip.stdout}}:32400/"
```

It will work remotely just fine

I think a choice has to be made on the networking.
network_mode: "host" makes the docker container look like it is on the host Ip (what I think).

If we change it to network bridge -network - plexguide, it will  need the advertise ip.

**Comment by Admin9705** [comment]
Hmm good point. Will look into it. It’s better to advertise for discovery

**Comment by Budman17r** [comment]
Generally speaking (I use the we because I may start contributing if that's
OK) use the internal Docker networks to connect the inner containers and
use nginx as an incoming port it allows ssl based connections to the inner
containers and setting up basic authentication. Allowing a more secure
method. I've heard an nginx fix may be coming. Should I start looking into
it too?

**Comment by Admin9705** [comment]
Ya, do you want contributer access?

**Comment by Budman17r** [comment]
Sure

**Comment by Admin9705** [comment]
Closing, check your email and I sent a PM via discord!
