### ISSUE TITLE
Config folder SABNZBD

### ISSUE THREAD

**Issue by nijode999** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#113]
Hello,

I used Plexguide. Now i see that SabNZBD default folder is /config/ and their it is downloading to. But i cant see the folder on filezilla or putty or x2go?

**Comment by Admin9705** [comment]
@nijode999 it's because it's using docker.  So it's not the real path, its /opt/appdata/sabnzbd for some info and /mnt/sabnzbd - hope that helps. reopen or comment if u have further issues.
