### ISSUE TITLE
Options for docker

### ISSUE THREAD

**Issue by Deiteq** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#37]
Hey @Admin9705,

Been looking at getting a Docker updater and found **watchtower** [https://github.com/v2tec/watchtower](url) might be what we're looking for.
Also, just checking out an auto install script called **mediabox** [https://github.com/tom472/mediabox](url) that has **watchtower** and **deluge-vpn** via **pia** (to use torrent through a vpn) included.

Maybe there's a way to incorporate some of this stuff to help streamline the process?

**Comment by Admin9705** [comment]
Agreed! Sounds like a good start.  I love how far this has come along.
