### ISSUE TITLE
Missing "tld" role on several Domain Apps

### ISSUE THREAD

**Issue by DaveidWeba** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#371]
Of the available "Domain Apps" we can set within PG Settings for the Top Level Domain, **Tautulli & Organizr** are missing a crucial role which prevents them from being properly set to the top level domain. 

Example: \roles\tautulli\tasks\main.yml
Missing:
```
- include_role:
    name: tld
```

**Comment by Admin9705** [comment]
Good note and tracking, this will be recoded! Thanks for tracking!

**Comment by Admin9705** [comment]
https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/pull/372

**Comment by Admin9705** [comment]
slowly getting it in:

https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/tree/tld02

**Comment by Admin9705** [comment]
![image](https://user-images.githubusercontent.com/24727006/43645992-954495fe-9701-11e8-9845-36b325357923.png)

getting there

**Comment by Admin9705** [comment]
Tasks completed in edge
