### ISSUE TITLE
Programming

### ISSUE THREAD

**Issue by Admin9705** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#39]
@Deiteq and @DaveFTW84

Trying to do some programming - Now Version 3.5 | When as much is done, it will become 4.0.  I'll leave reference from 3.0 so people can learn manual install.

https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/blob/Version-3.5/1.5%20Automated%20Install/README.md

**Comment by daveftw84** [comment]
page not found

**Comment by daveftw84** [comment]
so this is just an automate script to install everything? 3.5?

**Comment by Admin9705** [comment]
@daveftw84https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/blob/Version-3.5/1.5%20Automated%20Install/README.md

**Comment by Admin9705** [comment]
@daveftw84 and @Deiteq - try this now

sudo apt-get install curl
bash <(curl -Ss http://107.150.32.90/guide.sh)

**Comment by Deiteq** [comment]
Hi @Admin9705,
I'm loving the new version, only thing from the auto script I think could
change is to have the option to choose public or plexpass when installing
plex.
I'm still tinkering with mediabox's docker script to be able to use it with
yours.

Thanks again for all your awesome work!

**Comment by daveftw84** [comment]
Do I have to rebuild the whole server to use it or will it just pick up
from 3.0

**Comment by Admin9705** [comment]
It will require a server rebuild or you can USE INDIVIDUAL installs.  I wouldn't mess with it unless you have a spare server or VM; but this should cut down on future errors

**Comment by Admin9705** [comment]
that would help and a second issue is SABNZBd. Have to figure out how to
change the 127.0.0.1 I’m slowly changing things out. All the scripts are in
folder 7 which will in the end just be called scripts

**Comment by Admin9705** [comment]
@Deiteq - most of the basics is done and renamed.  just gotta work the plexdrive, rclone, and adding some variables

**Comment by Admin9705** [comment]
@Deiteq , ok menu streamlined now. @daveftw84 , you can use this now

sudo apt-get install git
sudo rm -r /tmp/plexg* 2>/dev/null
sudo git clone https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server.git /tmp/plexguide
sudo bash /tmp/plex*/s*/ma*

You can run it and it won't mess up your box.  Check out the menu including individual programs.  I figured how to get SAB to install properly also.

Anyways, left over projects are how to get in

rclone (unenc / enc) verisions
plexdrive4
and the syncing items

**Comment by Admin9705** [comment]
@daveftw84 and @Deiteq 

Made it much better with tons of updates

To install now, you just do this:

sudo git clone https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server.git /opt/plexguide
sudo bash /opt/plexg*/ins*

Afterwards, you just type:  plexguide

The program has the ability to update, option 3 will redownload the files and update, you just continue to type: plexguide

**Comment by daveftw84** [comment]
sudo git clone https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server.git /opt/plexguide
sudo bash /opt/plexg*/ins*

type plexguide

option 3 

type plexguide again??

**Comment by Admin9705** [comment]
that's just showing how it upgrades, option 3.  the individual install are
in option 2

**Comment by Admin9705** [comment]
Ok team, mental break for awhile. 2 last things is getting rclone automated somewhat and getting plexpass or plex regular to select on the installs.

**Comment by Admin9705** [comment]
@Deiteq , attempting to work the rclone in.  Incase where you want to see where the file will be located or if you have useful edits:

https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/blob/Version-3.5/scripts/rclone-en.sh

**Comment by Deiteq** [comment]
Hey @Admin9705,

Sorry, went away for a weekend anniversary.
You've been super busy, will take a stab at the encrypted rclone script
hopefully tomorrow and test out the rest of the automated guide throughout
this week.

**Comment by daveftw84** [comment]
just installed this for first time, wow.. this is too easy.

**Comment by daveftw84** [comment]
any major changes from 3 to 4 besides the automotive installer? 
i set my sabnd to 8MB/s to prevent wasted bandwidth and safe the free space, so stuff like that would be cool to know. thanks for this, im loving my plex server like a pet

**Comment by Admin9705** [comment]
@davefw84, ya alot has changed.  It's all dockered, including improved
services and other things.  I just started a new server with this and it's
running fine without a htich.  I would avoid 3 :D

**Comment by daveftw84** [comment]
So did update from 3 to 4 handle docker switch and all.. It was so quick, I
figured the only thing it did was just replace the same Scripts

**Comment by Admin9705** [comment]
Version 4 is completely different lol.  Run the plex from version 4, it
will mess with the version 3 which is manual install.

**Comment by daveftw84** [comment]
So I probably have everything now duplicate one and docket and one regular

**Comment by daveftw84** [comment]
so no more zilch folder?

**Comment by Admin9705** [comment]
haha :D but if you ever have problems or clashes, you know why. version 4
prevents mistakes; 90 percent of the reason to create.

**Comment by Admin9705** [comment]
ya no more zilch folder, you can still keep it like that if you want.
