### ISSUE TITLE
Problem installing rclone

### ISSUE THREAD

**Issue by Deiteq** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#40]
Still testing the auto install script as I've edited some of the scripts like **rclone-en.sh**.
Added **fail2ban** & **ufw** to the **dep.sh** as I feel they are both important to keep remote servers secure.
Still need to add details for hardening **fail2ban** with a way to permanently block ip's that are trying to hack the server via ssh.

One problem I found with trying to use option 2 for the rclone install is that unzip hasn't been installed yet so I've temporarily added it to **rclone-en.sh**.
Another problem is with **/dev/null** :-
`cp: target '/dev/null' is not a directory`
`mkdir: cannot create directory ‘/root/.config’: File exists`

Will send a pull request of all edits done so far for you to see if there's anything you want to add or change, but I still need to test it all.

**Comment by Admin9705** [comment]
Oh your doing great!  Did you see the test folder? I found some kind of script with the fail2ban stuff in it.  Did you notice the self updating option?  Does this allow you to make changes without my approval? I made you a collaborator.  The upside is if you make a change, you just type plexguide, 5, and poof... you can see it in action.  I run a VM with a snapshot so I can reset back for requiring major changes.  What kind of computer and os are you running.  I have VMWorkstation14 for windows if you require a copy and for mac, vmware fusion also.  I started figuring out this pull and push thing.  I'm using the github desktop and atomos for editing.  So easy to make and track changes.  Thanks for the second look, was losing my marbles.  You know how it is when you get caught up in your own works.  I fixed the api ban on my server.  You know what was the problem? For rclone move, I set the move to 30 seconds and loop.  That caused it to stop.  I changed to 30 sleep at start and then 1800 seconds for loop.  0 issues.  I made the updates to the manual guides.

**Comment by Admin9705** [comment]
@Deiteq think the work around is some kind of check variable, like if this folder exists, then skip. i'll have to do some research later.

**Comment by Deiteq** [comment]
@Admin9705 wow...I didn't notice the test folder but will have a tinker this week.
Have you had a look at **tom472**'s **mediabox.sh** script to see if it could help?
Notice you are using **127.0.0.1** as **hostname**, mediabox has a way of getting the servers actually ip, I've added part of it below:-

```
# Get local Username
localuname=`id -u -n`
# Get PUID
PUID=`id -u $localuname`
# Get GUID
PGID=`id -g $localuname`
# Get Hostname
thishost=`hostname`
# Get IP Address
locip=`hostname -I | awk '{print $1}'`
# Get Time Zone
time_zone=`cat /etc/timezone`

# CIDR - this assumes a 255.255.255.0 netmask - If your config is different use the custom CIDR line
lannet=`hostname -I | awk '{print $1}' | sed 's/\.[0-9]*$/.0\/24/'`
# Custom CIDR (comment out the line above if using this)
# Uncomment the line below and enter your CIDR info so the line looks like: lannet=xxx.xxx.xxx.0/24
#lannet=
```

All this scripting code is going over my head, there's so much I need to learn to be able to pinpoint problems and help find solutions.
I'm super impressed at how much you know!

**Comment by Admin9705** [comment]
@Deiteq at the end of the week, I'll start looking more into it.  What part does the 127 play in that your talking about.  Aware it's a local host.  The stuff in the test folder is just stuff I found.  Eh, try to regarding knowledge.  You saw how far back we started out at.  I'm glad your assisting.  I'm learning on the go.  Just really glad to see how well this is working out.

**Comment by Deiteq** [comment]
@Admin9705 ,  
Just managed to find the time to get back on this project.
I forgot to answer your previous question, I have an ASUS i5-3570K PC with 16GB RAM that I'm forcing myself to run Ubuntu on and I'm using VirtualBox for the VM's as it's free but it's not currently in use as it's connected to the TV in the lounge so can't use it when people want to watch normal TV!
Tried using my old Acer Aspire i3-350M laptop but I'm not sure if it's powerful enough to do much VM stuff with as it only has 4GB RAM.
I have 2 remote servers with different company's that I can tinker with using my Android tablet and SSH Juice, my current live one is with Netcup and my old one is with ZXPlay, but ZXHost upgraded their equipment last week and my server has been down for over 5 days now due to their system not sending me new temporary root passwords after a fresh install of Ubuntu so I am unable to access it to test out your script!
ZXPlay/Host haven't been great at responding to already open tickets, may have to close my ticket and open a new one as I seem to get a response quicker then, but at the same time I think there is only one guy running and maintaining it as he's the only one to reply!
The reason why I have two remote servers is because I was having issues running Plex through the ZXPlay server and wanted to see if Netcup could handle it better using SSD and more RAM, plus their bandwidth is unlimited so perfect for downloads and uploads to gdrive, only downside is the I only have 60GB SSD so there's only about 20GB free space left for downloads (I'm assuming Plex is taking a chunk of the space for all the metadata and stuff!) 

I have to admit, using VirtualBox isn't smooth sailing as hoped, I have issues with the network settings and have to try a few different setups to be able to 1. get it connecting to the internet or 2. access it via SSH.
I may have to take you up on your VMWorkstation offer!

Anyway, I'm gonna have another go at using the VM on my laptop and if it's being a PITA then I'll get my PC up and running again whilst I wait for ZXPlay to sort their end out.

**Comment by SilverSix311** [comment]
What I would recommend is if you have/can acquire Windows 10 Professional is to use that with Hyper-V. One VM running Ubuntu/Debian/CentOS only uses like 512mb RAM making it a bit more manageable. You can also install bash on windows and actually just run his stuff locally I think.

As far as your 60GB SSD, depending on the size of your library, you WILL run out of space. I have a 28TB library and i have 200GBs used on my SSD RAID0 just for Plex. Mind you I have a few subsystems running on that VM such as Sonarr/Ombi/Couchpotato/etc. I have a dedicated seedbox VM as well. So ya just be careful. You could also take a look at an R610 with a low power cpu, or an R310. They are super cheap on ebay and will give you PLENTY of headroom for power and RAM (Assuming you buy enough, its also not very expensive)

**Comment by Admin9705** [comment]
@Deiteq post your email and i'll delete it or you can send it to me on reddit at admin9705.

**Comment by Admin9705** [comment]
@SilverSix311 , ya that's another solution.   I have professional and haven't used hyper-v for it.  That is another way around it.  Your right about space, plex will eat most of it.  a vps is not a good solution for a semi-large library.  the split function works better.  home cpu does the upload and remote server acts as the server.  the HD i have is a 480SSD, but my virtual machine has a 7TB vm, so when it backlogs tons of crap, i dont' have issues that interfere with the server.  I really appreciate you dropping by and contributing to the discussion.

**Comment by Deiteq** [comment]
@SilverSix311 & @Admin9705 , Thanks for the advice, originally I was just going to use my remote server purely as a plex server and have usenet running at home but electricity here in Barcelona is silly expensive, worked out cheaper to have a remote server run 24/7 doing everything.
I have only about 5TB on my gdrive at the moment,  hmmm just remembered that I have emby running on that server too, so maybe that's taking a chunk of the storage as well?

With Netcup for an extra 5€ per month I can get 250GB storage with a 2.5TB bandwidth limit but that shouldn't be a problem if I have plex running off the storage drive with transcoding running off the SSD along with usenet also, if that's possible?!

Or  maybe I could use my raspberrypi 3 to do the downloads when we're not using it for plex and iptv?

@Admin9705 I sent you a pm on reddit.

**Comment by Deiteq** [comment]
Just running through Version 4's Rclone install section and I'm seeing this message when using the encrypted install:-
`bash: /opt/plexguide/script/docker-no/rclone-config.sh: No such file or directory`

Maybe I've missed something, will try figuring it out.

**Comment by Deiteq** [comment]
I think **rclone-basic.sh** is missing the encrypted unionfs mount service, will try adding that to see if it helps.

**Comment by Deiteq** [comment]
**rclone config** is missing from **rclone-en.sh**, not sure if I sent a pull request yet for it?

**Comment by Admin9705** [comment]
@Deiteq , i'll merged them all

**Comment by Deiteq** [comment]
@Admin9705 thanks, I just did another one to separate the rclone instructions with **rclone config**.

**Comment by Admin9705** [comment]
Ok, looks like rclone is good to go! If we have any issues, just comment and it will reopen
