### ISSUE TITLE
Empty Sonarr/Radarr will cause PGTrak script to fail

### ISSUE THREAD

**Issue by DaveidWeba** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#401]
On a brand new server, if a user just got finished installing Sonarr & Radarr then attempted to deploy PGTrak it will fail due to being unable to retrieve the current list of shows/movies.

**To Reproduce**
1. Install a fresh copy of Sonarr & Radarr without importing data
2. Deploy & run PGTrak
3. The following errors should occur: 
`ERROR - traktarr - get_objects - Aborting due to failure to retrieve Sonarr shows list`
`ERROR - traktarr - get_objects - Aborting due to failure to retrieve Radarr shows list`
![](https://i.imgur.com/h0wOX7w.png)
**Once you add something to Sonarr/Radarr, the script proceeds to run without issue.**
![](https://i.imgur.com/XRHAi1N.png)

**Comment by Admin9705** [comment]
Rgr, will have program display note.

**Comment by Admin9705** [comment]
updated the program. good to go.
