### ISSUE TITLE
Ubooquity Deployment & Ports

### ISSUE THREAD

**Issue by NotTeresa** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#408]
Issue:
401 http error due to missing admin password on deployment.

How to get the issue?
Simply install ubooquity with a clean appdata

Fixes to be made:
Open up port 2203 so people can set their admin password, thus enabling access to the library interface (port 2202).

**Comment by Admin9705** [comment]
![image](https://user-images.githubusercontent.com/24727006/43555842-8539fb8c-95ca-11e8-8bfc-255c9ec1998f.png)
