### ISSUE TITLE
2nd HDD bugs out because unionfs is faster than hdd mounting on startup

### ISSUE THREAD

**Issue by Klaufi** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#413]
On startup the 2nd hdd bugs out because pgblitz recreates folders in the hdd's name folder creating a folder and forcing the hdd to add a extra number in the name. 

![image](https://user-images.githubusercontent.com/13190627/43596352-9870ece8-966e-11e8-87a2-a1d19c57aaa0.png)

**What is affected by this bug?**
UnionFS

**When does this occur?**
Reboot

**Comment by Admin9705** [comment]
sounds good, will look into a unionfs startup delay

**Comment by Admin9705** [comment]
no other reports of issues and tested.
