### ISSUE TITLE
Plex Updates - ADVERTISE_IP env variable gets reset

### ISSUE THREAD

**Issue by zhdenny** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#418]
**Describe the bug**
Whenever Plex Container is updated, the environmental variable "ADVERTISE_IP" gets reset to http://IP_Address:32400. This is an issue for anyone who uses CDN.....where this variable needs to be https://plex.domain.com:443

**To Reproduce**
1. Check Plex settings under "Custom Server Access URLs". If using CDN, it will be https://plex.domain.com:443
2. Plex Container gets updated
3. Check Plex settings again under "Custom Server Access URLs". The setting has been reset to http://IP_Address:32400. This makes CDN no longer work unless you set the address again.

**Expected behavior**
CDN settings should survive Plex Container Updates

**Screenshots**
If applicable, add screenshots and/or .gif to help explain your problem.

**What is affected by this bug?**

**When does this occur?**
Whenever the Plex Container is updated

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.16Stable
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: Move+PGDrive/Move+PlexDrive/
  * Using Traefik: Yes
  * Domain DNS Provider: CloudFlare

**Logs**
If applicable provide the output from relevant logs and/or the output from the `pglog` command

**Additional context**
Detailed explanation, related issues, suggestions how to fix, links for us to have context

**Comment by Admin9705** [comment]
we'll still figure this out before 6.027 is released.

**Comment by NotTeresa** [comment]
Not a bug, but I will create a PR soon to add CDN options for the Plex container.

**Comment by Admin9705** [comment]
any luck @NotTeresa ?

**Comment by NotTeresa** [comment]
@Admin9705 At the moment still coding the entire PGAuth stuff, my focus afterwards will be on PGBlitz automation, I'm not releasing any CDN options until I fully developed PGCDN as well.
