### ISSUE TITLE
Support for syncthing

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#425]
Please add syncthing as a supported utility.

https://hub.docker.com/r/linuxserver/syncthing/

**Comment by Admin9705** [comment]
no problem, this will be tracked and when can :D

**Comment by Admin9705** [comment]
https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/pull/430

**Comment by Admin9705** [comment]
added by @MBCorp
