### ISSUE TITLE
Expose Traefik dashboard externally

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#426]
I'd like to have the Traefik proxy dashboard (running on port 8080) exposed and proxied through Traefik.  is this possible?

Some information on this here https://medium.com/@xavier.priour/secure-traefik-dashboard-with-https-and-password-in-docker-5b657e2aa15f

**Comment by MBCorp** [comment]
Hi ookla-ariel-ride,

Have followed the steps and now have the traefik dashboard exposed with basic auth. But just tell me: Why do you want this? It's not like their is so much usefull information. And you can't edit anything from the dashboard anyways?

**Comment by Admin9705** [comment]
Ya we'll pass on this. we have portainer that displays what you have running. the input of the password generation is the complicated step. thanks for the idea on this; but you can always code and add. the hard part is the password gen.
