### ISSUE TITLE
modify Plex configuration to allow use of /dev/shm for transcode

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#428]
Add docker configuration to allow transcode directory mapping to host /dev/shm

per https://github.com/ajkis/scripts/wiki/best-plex-rclone-mount-settings section "Plex Server Transcoder settings"

**Comment by Admin9705** [comment]
this can be easy. we'll add the location and then you can just change the transcoder location.

**Comment by MBCorp** [comment]
This have been "addressed" in one of the latest merges. use /ram_transcode in plex setting under: "Transcoder temporary directory" - to store the plex transcoding temporary files on ram instead of disk (to maybe save som disk I/O)
