### ISSUE TITLE
Setting up PG AppGuard deletes Radarr, Sonarr, NZBGet

### ISSUE THREAD

**Issue by Klaufi** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#433]
**Describe the bug**
Setting up PG AppGuard deletes Radarr, Sonarr, NZBGet

**To Reproduce**
Install PG AppGuard with listed apps installed 

**Screenshots**
![image](https://user-images.githubusercontent.com/13190627/43681801-b45e5044-984e-11e8-9f15-5e5816d25b55.png)

**What is affected by this bug?**
Sonarr, NZBGet, Radarr

**When does this occur?**
At setup

**Additional context**
Fix is just let us pick what is getting installed so it just doesnt skip these apps.

**Comment by Admin9705** [comment]
Makes sense, it's because the formatting has changed.  I'll make sure to address it.

**Comment by Admin9705** [comment]
https://plexguide.com/threads/6-027-edge-update-release-later-today.1746/post-9368

**Comment by Admin9705** [comment]
fixed 6.047; removed appguard. use wckd authentication
