### ISSUE TITLE
having some issues with HW transcoding

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#442]
I noticed that HW transcoding was added some time ago to the Plex container configuration.  However, on my system, it was not working.  

I did some troubleshooting and added the user the plex docker container runs under to the "videos" Linux group.  I also manually added /dev/dri to the devices area under runtime resources in portainer and re-deployed plex.  that fixed hw transcoding for me.

not sure if this can be reproduced on other systems, but I am just wondering if my system is an anomaly or if this is a problem that others are experiencing too.

**Comment by MBCorp** [comment]
When purchasing plexpass - that is required to use HW transcoding - you need to redeploy the plex container in order for it to pick up correctly.

**Comment by ookla-ariel-ride** [comment]
@MBCorp thanks, that fixed it.
