### ISSUE TITLE
RuTorrent Remote Change

### ISSUE THREAD

**Issue by Admin9705** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#446]
Submitted by member (jphandler), make fix for questions

Create another image
https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/pull/445

**Comment by Migz93** [comment]
Whilst creating the other image can someone fix the rutorrent volume mapping.
Sonarr/radarrs path mappings are /mnt/rutorrents to /downloads
But rutorrent is configured as /mnt/rutorrent to /downloads

It's missing an "S" on the end, which means when someone deploys rutorrent it wont work with sonarr/radarr as the mappings are different.

**Comment by doublechek** [comment]
> Whilst creating the other image can someone fix the rutorrent volume mapping.
> Sonarr/radarrs path mappings are /mnt/rutorrents to /downloads
> But rutorrent is configured as /mnt/rutorrent to /downloads
> 
> It's missing an "S" on the end, which means when someone deploys rutorrent it wont work with sonarr/radarr as the mappings are different.

I second this finding.  I make the change everytime in portainer. It would be helpful to have a fix in the ansible volume maps as well.

**Comment by Admin9705** [comment]
![image](https://user-images.githubusercontent.com/24727006/44298935-a3c4ca80-a2ba-11e8-8bf3-0d9219dcafad.png)

fixed in 6.037. reopen ticket if u spot issues
