### ISSUE TITLE
Implement Firewall Correctly

### ISSUE THREAD

**Issue by Admin9705** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#45]
So disabled the firewall instructions and fail2ban until everything is configured correctly.  It was blocking rutorrent.  Probably should be a simple fix.

**Comment by Admin9705** [comment]
@Deiteq , create a secure server menu item, but does not configure. have to ensure firewall is open for certain ports.  another project :(

**Comment by Admin9705** [comment]
@Deiteq , still have it disabled.  I created a security section.  Be able to drop stuff there futurewise.

**Comment by Deiteq** [comment]
@Admin9705 , have you looked at tom472's mediabox script?
He found a way to use iptables to route only torrent traffic through vpn, maybe iptables could help in this situation?

**Comment by Admin9705** [comment]
@Deiteq, looked at it briefly.  Once we come up with a feasible test solution, should be an easy add.

**Comment by Deiteq** [comment]
For anybody wondering, I'm currently working on implementing Deluge with PIA vpn from [https://github.com/binhex/arch-delugevpn](url), hope to get it working so it may replace RuTorrent.

**Comment by Admin9705** [comment]
@Deiteq so got phase 1 done... implement reverse proxy. phase 2 is ssl and then then firewall & jail thing
