### ISSUE TITLE
netdata warning - high cpu usage 

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#46]
disk_inodes.mnt_rclone critical: current disk inode useage

http://an0nplex.ddns.net:19999

**Comment by daveftw84** [comment]
disk - sda
--
disk_backlog.sda  average of the kernel estimated disk backlog, for the last 10 minutes role: sysadmin   jump to chart | warning when$this > $green * (($status >= $WARNING) ? (0.7) : (1))critical when$this > $red * (($status == $CRITICAL) ? (0.7) : (1))db lookupaverage of all values , of chart disk_backlog.sda, starting 10 minutes ago and up to now, with options unaligned.green threshold2000 backlog (ms)red threshold5000 backlog (ms)check every1 minuteexecute/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on recovery 15 minutes, multiplied by 1.2, up to 1 hoursource112@/opt/netdata/etc/netdata/health.d/disks.conf | warning when | $this > $green * (($status >= $WARNING) ? (0.7) : (1)) | critical when | $this > $red * (($status == $CRITICAL) ? (0.7) : (1)) | db lookup | average of all values , of chart disk_backlog.sda, starting 10 minutes ago and up to now, with options unaligned. | green threshold | 2000 backlog (ms) | red threshold | 5000 backlog (ms) | check every | 1 minute | execute | /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on recovery 15 minutes, multiplied by 1.2, up to 1 hour | source | 112@/opt/netdata/etc/netdata/health.d/disks.conf
warning when | $this > $green * (($status >= $WARNING) ? (0.7) : (1))
critical when | $this > $red * (($status == $CRITICAL) ? (0.7) : (1))
db lookup | average of all values , of chart disk_backlog.sda, starting 10 minutes ago and up to now, with options unaligned.
green threshold | 2000 backlog (ms)
red threshold | 5000 backlog (ms)
check every | 1 minute
execute | /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on recovery 15 minutes, multiplied by 1.2, up to 1 hour
source | 112@/opt/netdata/etc/netdata/health.d/disks.conf
disk_util.sda  the percentage of time the disk was busy, during the last 10 minutes role: sysadmin   jump to chart | warning when$this > $green * (($status >= $WARNING) ? (0.7) : (1))critical when$this > $red * (($status == $CRITICAL) ? (0.7) : (1))db lookupaverage of all values , of chart disk_util.sda, starting 10 minutes ago and up to now, with options unaligned.green threshold90 % of time workingred threshold98 % of time workingcheck every1 minuteexecute/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on recovery 15 minutes, multiplied by 1.2, up to 1 hoursource90@/opt/netdata/etc/netdata/health.d/disks.conf | warning when | $this > $green * (($status >= $WARNING) ? (0.7) : (1)) | critical when | $this > $red * (($status == $CRITICAL) ? (0.7) : (1)) | db lookup | average of all values , of chart disk_util.sda, starting 10 minutes ago and up to now, with options unaligned. | green threshold | 90 % of time working | red threshold | 98 % of time working | check every | 1 minute | execute | /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on recovery 15 minutes, multiplied by 1.2, up to 1 hour | source | 90@/opt/netdata/etc/netdata/health.d/disks.conf
warning when | $this > $green * (($status >= $WARNING) ? (0.7) : (1))
critical when | $this > $red * (($status == $CRITICAL) ? (0.7) : (1))
db lookup | average of all values , of chart disk_util.sda, starting 10 minutes ago and up to now, with options unaligned.
green threshold | 90 % of time working
red threshold | 98 % of time working
check every | 1 minute
execute | /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on recovery 15 minutes, multiplied by 1.2, up to 1 hour
source | 90@/opt/netdata/etc/netdata/health.d/disks.conf

disk_inodes._mnt_rclone  current disk inode usage role: sysadmin   jump to chart | warning when$this > (($status >= $WARNING) ? (80) : (90))critical when$this > (($status == $CRITICAL) ? (90) : (98))calculation$used * 100 / ($avail + $used)check every1 minuteexecute/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on escalation 1 minute, on recovery 15 minutes, multiplied by 1.5, up to 1 hoursource26@/opt/netdata/etc/netdata/health.d/disks.conf | warning when | $this > (($status >= $WARNING) ? (80) : (90)) | critical when | $this > (($status == $CRITICAL) ? (90) : (98)) | calculation | $used * 100 / ($avail + $used) | check every | 1 minute | execute | /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on escalation 1 minute, on recovery 15 minutes, multiplied by 1.5, up to 1 hour | source | 26@/opt/netdata/etc/netdata/health.d/disks.conf
warning when | $this > (($status >= $WARNING) ? (80) : (90))
critical when | $this > (($status == $CRITICAL) ? (90) : (98))
calculation | $used * 100 / ($avail + $used)
check every | 1 minute
execute | /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on escalation 1 minute, on recovery 15 minutes, multiplied by 1.5, up to 1 hour
source | 26@/opt/netdata/etc/netdata/health.d/disks.conf

**Comment by daveftw84** [comment]
http://an0nplex.ddns.net:19999

**Comment by Admin9705** [comment]
ya i'm looking at it.  i'm just seeing that it's saying your disk is tasked.   I really don't look that much into net data.  I look at the cpu and ram usage, along with the speeds.  Beyond that, it's beyond me lol.

**Comment by daveftw84** [comment]
i notice im paying alot more then you for less specs, where do you get your
server if you dont mind me asking?

**Comment by daveftw84** [comment]
i scheduled a hard drive test in a hour, so ill see if its a failing hard
drive or not

**Comment by daveftw84** [comment]
one last thing, whats a good bitrate to have content maxed out at?
