### ISSUE TITLE
Can’t install WebTools 3.0

### ISSUE THREAD

**Issue by KrisEkman** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#470]
**Describe the bug**
When trying to install WebTools 3.0, it never runs and errors out with the message “webtools: Not Installed”.

**To Reproduce**
1. Run: Plex Enhancements Tools --> WebTools 3.0

**Screenshots**
![4d51004d-d502-4e71-a02d-f7d71e17ed41](https://user-images.githubusercontent.com/927259/44007151-d98f86ce-9e90-11e8-8094-1533eeca0866.png)

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 16.04
  * Plexguide Version: 6.0.30 v2! Stable (error also available in previous builds)
  * Plexguide Server Type: Remote VPS
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: Move+PGDrive
  * Using Traefik: No

**Comment by Admin9705** [comment]
thanks for the heads up. will update in next update!

**Comment by Admin9705** [comment]
worked on for 6.033 didn't have time to test. if you can verify it works. also will streamline interface for the enhancements menu. weird loop bugs there.

**Comment by KrisEkman** [comment]
Can confirm that WebTools now installs correctly in 6.033. Thanks!
