### ISSUE TITLE
Move.sh script has an extra `--`

### ISSUE THREAD

**Issue by Migz93** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#475]
Move.sh script has an extra `--` in it which breaks the standard move script.

1. Deploy PG with the normal move.sh script
2. No files will upload.
3. Check service status and you will see an error.

Expected behavior:
Files should upload and there should be no error in the service status.

Additional context:
https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/blob/Edge/roles/rclone_un/templates/move_script.js2
Line 11, just after the --min-age 2m argument there is an extra `--` with no argument with it, the extra `--` needs to be removed.

No idea how to do the new fork process to fix this myself so i'll just submit a bug report.

**Comment by Admin9705** [comment]
fixed!
