### ISSUE TITLE
Extra "Empty Folders" created during Mass Backup on Longer/Bigger Applications be Backed Up

### ISSUE THREAD

**Issue by albatross1** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#476]
**Describe the bug**
the mass backup solution designed to back up each application by creating a folder for that application the minuet it uploads, as opposed to the day it uploads? Creates a lot of additional folders, making it harder to find one application, that is in what folder. Weird as the normal back up applied after installation of a application stay all within one folder. Which seems cleaner. 

**To Reproduce**
1. Go to 'PG Backup & Restore'
2. Click on 'Mass Backup'
3. See error [Watch folder being created with nothing in them. Specifically on larger back up that take longer amounts of time.]

**Expected behavior**
Folder with date created, all backup .tar files in folder with date.

**Screenshots**
If applicable, add screenshots and/or .gif to help explain your problem.
https://cdn.discordapp.com/attachments/463958711501717506/478564255596150811/Capture.png

**What is affected by this bug?**
The backup feature.

**When does this occur?**
When Mass backup is selected. During it's back up process. 

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu [16.04]
  * Plexguide Version: 6.xx [6.030 V3]
  * Plexguide Server Type: [Remote Dedi VM]
  * Plexguide Edition: [GdriveE]
  * Plexguide Mount System: [Move+PGDrive]
  * Using Traefik: [Yes]
  * Domain DNS Provider:[GoDaddy]

**Logs**
N/A

**Additional context**
Detailed explanation, related issues, suggestions how to fix, links for us to have context

May look into folder creation on selection of application checking how often it's pinged against that to see if it's creating folders on false entries or not. On request I code take a closer look at the code to give my opinion.

**Comment by Admin9705** [comment]
saw you pic. no further reports of this. will test myself and then close out in a few days.  might have been something from old installs.

**Comment by Admin9705** [comment]
closing this. haven't seen the error and not reproduced. please open ticket if you encounter again
