### ISSUE TITLE
Error installing Traefik reverse proxy with 6.0.31

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#477]
with 6.0.31 beta I cannot install traefik reverse proxy.  I get the following error:

TASK [traefik : Remove Traefik] ************************************************
Monday 13 August 2018  14:06:10 -0500 (0:00:00.086)       0:00:37.021 *********
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Cannot have both the docker-py and docker python modules installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module"}
        to retry, use: --limit @/opt/plexguide/pg.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=15   changed=7    unreachable=0    failed=1

**Comment by Admin9705** [comment]
To fix the error, this error follow: https://plexguide.com/threads/6-031-beta-1-%E2%80%93-released.1791/post-9617
