### ISSUE TITLE
Sonarr4k Failed Install

### ISSUE THREAD

**Issue by jak64950** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#478]
**Describe the bug**
Sonarr4k fails to install due to an error in core.yml file.

  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.031 Beta1
  * Plexguide Server Type: [Local Dedi]
  * Plexguide Edition: [Gdrive]
  * Plexguide Mount System: [Move+PGDrive]
  * Using Traefik: [Yes]
  * Domain DNS Provider:[CloudFlare]

**Additional context**
Looks like the error has to do with creating folders for mp4_automator, specifically if the user inputs "3" but for some reason, that condition is undefined or something.

**Comment by Admin9705** [comment]
fixed! update to edge now or 6.032 when it's out. there was a bad line of code in the wrong area. surprised no one reported
