### ISSUE TITLE
VPN Options

### ISSUE THREAD

**Issue by jak64950** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#479]
**Is your feature request related to a problem? Please describe.**
Every time delugeVPN is installed I am forced to select a PIA ovpn. After install I have to delete the PIA ovpn and change docker variables from PIA to custom and the port number.

**Describe the feature/solution you'd like**
Perhaps the install process could ask if you want to use PIA or custom provider, and input providers port number for those of us who don't use PIA. Honestly, even just not being forced to download a PIA ovpn would be a step in the right direction.

**Comment by Admin9705** [comment]
This is known, but the person who worked it is on a vacation.  It's difficult to enter the custom providers.  I coded 0 of this; so it's unknown to me.  If you know how to code or resolve for more providers; that is the only solution.  It will stay like this until some makes changes :D  Thanks for the note!
