### ISSUE TITLE
Solo Backup Plex - An exception occurred during task execution.

### ISSUE THREAD

**Issue by albatross1** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#482]
**Describe the bug**
When trying to do a solo back up of simply Plex itself, I'm getting the following error. "An exception occurred during task execution. To see the full traceback, use -vvv                                   . The error was: OSError: [Errno 2] No such file or directory: '/opt/appdata/ple                                   x/database/Library/Application Support/Plex Media Server/Metadata/TV Shows/3/7d2                                   f17f99b6fcf03d5b33fca86538543f831ae1.bundle/Contents/_combined/seasons/2/episode                                   s/22/thumbs/com.plexapp.agents.localmedia_892e7d5c9730b3e952b5857b5380be594c5435                                   ee'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error when writing tar                                   .tar archive at /mnt/hdd/pgops/plex.tar: [Errno 2] No such file or directory: '/                                   opt/appdata/plex/database/Library/Application Support/Plex Media Server/Metadata                                   /TV Shows/3/7d2f17f99b6fcf03d5b33fca86538543f831ae1.bundle/Contents/_combined/se                                   asons/2/episodes/22/thumbs/com.plexapp.agents.localmedia_892e7d5c9730b3e952b5857                                   b5380be594c5435ee'"}"

**To Reproduce**
1. Go to 'PG Backup & Restore'
2. Click on 'Solo Backup'
3. See error [After selecting Plex]

**Expected behavior**
A very long wait, and a folder created in gdrive with ple
![capture](https://user-images.githubusercontent.com/1198510/44099893-adb1bd66-9fb1-11e8-8e6d-afceb6495d5c.png)
x.tar

**Screenshots**
See Attached for picture of error.

**What is affected by this bug?**
Solo Backup for Plex

**When does this occur?**
When Solo Backup is selected, then plex, you wait about 3/8 minuets, then the error occurs.

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
Operating System: Ubuntu [16.04]
Plexguide Version: 6.xx [6.032 EDGE]
Plexguide Server Type: [Remote Dedi VM]
Plexguide Edition: [GdriveE]
Plexguide Mount System: [Move+PGDrive]
Using Traefik: [Yes]
Domain DNS Provider:[GoDaddy]

**Logs**
N/A

**Additional context**
It's getting hung up specifically on large plex databases, when creating the .tar itself. No other application has this error.

**Comment by Admin9705** [comment]
if you have some time, it's a shell command. there is a way to add on a skip error tag for backing up... if you have time to check it out! multitasked :D

**Comment by albatross1** [comment]
Reboot, and first thing I did was stop Plex an it's still throwing same error. Doing it manually as well. I even updated to newest Edge, just to see if anythings changes. An I'm still getting same error.

**Comment by Admin9705** [comment]
it might be some off file that your having issues with.  would need to find the ignore error command

**Comment by Admin9705** [comment]
ya i just did a mass back up and no issues :|

**Comment by timekills** [comment]
I'm receiving the same (well, similar - it is an error when backing up a Metadata/TV Shows file, specifically /opt/appdata/plex/database/Library/Application Support/Plex Media Server/Metadata/TV Shows/f/6aee27ae8da036af1f7d07b83ba669fc433cc27.bundle/Contents/_combined/posters/com.plexapp.agents.localmedia_d15b2b2a94810693bedb9b715660007e864d882c)

I assume the shell command and skip error tag is in reference to the comment in the error log:
"to retry, use: --limit @/opt/plexguide/pg.retry"
however, I'm unsure how to run the backup through a separate shell command vice the backup script inside plexguide to apply that limiter.

Obviously, I'd prefer to see why the error is thrown and repair it, but would appreciate the instructions for running from shell to try the limiter.
