### ISSUE TITLE
Ombi4k Not Connecting

### ISSUE THREAD

**Issue by jak64950** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#483]
**Describe the bug**
Ombi4k will not load. Getting 404 page not found.

**Additional context**
To fix, the port configuration needs to be changed from 0.0.0.0:3580->3580 to 0.0.0.0:3580->3579 and traefik.port needs changed from 3580 to 3579.

**Comment by Admin9705** [comment]
issue fixed! thanks for letting me know!

![image](https://user-images.githubusercontent.com/24727006/44123156-f33eacde-9ff4-11e8-9369-fc9ece7cf46d.png)

i changed to 3574 like how the others are.  I didn't build this one, but see how the error was made!
