### ISSUE TITLE
6.033 breaks install

### ISSUE THREAD

**Issue by kinv** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#487]
**Describe the bug**

After updating from 6.032 - 6.033 I get the following error
bash: /opt/plexg*/sc*/ins*: No such file or directory
bash: /opt/plexguide/roles/log/log.sh: No such file or directory
bash: /opt/plexguide/roles/ending/ending.sh: No such file or directory

After trying to deploy (plexguide) the error
bash: /opt/plex*/scri*/menu.sh: No such file or directory

I hope this does not mean I have lost my entire setup?

**To Reproduce**
I guess update 6.032 > 6.033 to see.

**Expected behavior**

Update and deploy as usual

**What is affected by this bug?**

plexguide

**When does this occur?**

on update

Screenshots

![screenshot from 2018-08-15 15-27-00](https://user-images.githubusercontent.com/42412447/44153429-250bcf8e-a0a0-11e8-9530-014d677222cc.png)
![screenshot from 2018-08-15 15-28-35](https://user-images.githubusercontent.com/42412447/44153447-33a69c86-a0a0-11e8-8a4a-8933567f228e.png)

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.033 Stable
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: PGBlitz
  * Using Traefik: Yes
  * Domain DNS Provider: GoDaddy

**Additional context**

I guess its an issue with paths? I really have no clue lol. Bonus points if you can give me advice on how to retrieve all my setup (if possible) lol (only had this server a day no backup yet)

EDIT - My plex server is still running despite this error.

Thanks!

**Comment by WildWayz** [comment]
Hi
Not a problem - sometimes happens. If it does, just re-run the installer:

sudo wget https://plexguide.com/install.sh && sudo bash ./install.sh

It'll fix it and you won't lose data.

**Comment by kinv** [comment]
Hi, I ran the command and it spat out this error;

fatal: destination path '/opt/plexguide' already exists and is not an empty directory

I imagine I need to delete that directory first, but assume that will delete all my configs so I will just leave it till I get some confirmation on that.

Thanks, really appreciate help :)

**Comment by WildWayz** [comment]
Yep fine to delete that folder .. configs are stored outside of that apart from the rclone configs if you've changed it. Just rename the folder to make sure.

Top of the install page on the site mentions it is safe to remove it :)

**Comment by WildWayz** [comment]
Hey I was the same as you a few months back. You learn fast though :)

**Comment by Admin9705** [comment]
Just run pgupdate
