### ISSUE TITLE
Cannot install DelugeVPN

### ISSUE THREAD

**Issue by jak64950** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#489]
**Describe the bug**
Under option to install programs, delugevpn is not listed. Therefore it can't be installed.

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
   * Plexguide Version: 6.032

**Comment by lunchingfriar** [comment]
Same thing with 6.033...

**Comment by lunchingfriar** [comment]
I worked around it with the following command:

sudo ansible-playbook /opt/plexguide/pg.yml --tags "delugevpn"

**Comment by jak64950** [comment]
Awesome, thanks

**Comment by Admin9705** [comment]
it will be pushed in the next update, it's because of the submenu; but easy to deal with.

**Comment by Admin9705** [comment]
ok fixed, just type vpn
