### ISSUE TITLE
AppGuard doesn't work

### ISSUE THREAD

**Issue by lunchingfriar** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#490]
**Describe the bug**
Enabling or resetting AppGuard has no effect.  Traefik does not prompt for usernames and passwords.

**To Reproduce**
Enable or reset AppGuard.

**Expected behavior**
I expected to be prompted for a username and password.  

**What is affected by this bug?**
Netdata and Heimdall are wide open to the world.  

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 16.04
  * Plexguide Version: 6.033
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: GDrive
  * Plexguide Mount System: Move+PlexDrive
  * Using Traefik: Yes
  * Domain DNS Provider: CloudFlare

In /opt/plexguide/roles/[netdata | heimdall]/tasks/core.yml, a line should be added under default_labels:

traefik.frontend.auth.basic: "{{auth.stdout}}"

After making this change and redeploying the roles, usernames and passwords work as expected.

Also, **THIS USED TO WORK**, but somebody removed the code.  A lot of working code seems to be disappearing from this project without warning or explanation...

**Comment by Admin9705** [comment]
Ya it’s because of massive rewrites. Appguard hasn’t been updated yet

**Comment by Admin9705** [comment]
we are testing the new authentication method released; this will probably scrap appguard in the end

**Comment by Admin9705** [comment]
remove it from 6.047; expanding wick auth
