### ISSUE TITLE
6.033: Backup/restore not working

### ISSUE THREAD

**Issue by jphermans** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#491]
**Describe the bug**
6.033: Backup and restore does not work in GCE version

**To Reproduce**
Go in menu to Backup and restore and select it.
Nothing happens and it has still the old (blue) menu.

**Screenshots**
<img width="513" alt="screen shot 2018-08-15 at 22 10 24" src="https://user-images.githubusercontent.com/735103/44170727-7caea300-a0d8-11e8-923e-5bcc44f31a6f.png">
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.033 [Stable]
  * Plexguide Server Type: [Remote Dedi/Remote VPS]
  * Plexguide Edition: [GCE]
  * Plexguide Mount System: [Move+PGBlitz]
  * Using Traefik: [Yes]
  * Domain DNS Provider:[Gandi]

**Comment by Admin9705** [comment]
thanks for the notification; will check into it

**Comment by Admin9705** [comment]
I updated GCE. Please type of update and install 6.034. Reopen ticket off u have further problems :D
