### ISSUE TITLE
Heimdall not Saving settings

### ISSUE THREAD

**Issue by clinch123** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#493]
**Describe the bug**
Heimdall launches in the browser, however I am unable to change any settings. Looking at the files all files have had ownership given to 911:911? This is not one of my users or groups and appears to be set from Ansible as I chown everything to correct then run Ansible and it changes.

**To Reproduce**
1. Install heimdall
2. Browse to heimdall
3. Attempt to change settings
4. Cant

**Expected behavior**
Expect to be able to change settings

**Screenshots**
chris@ovh-dedi:/opt/appdata$ ls -l
drwxr-xr-x  7   911   911 4096 Aug 16 01:05 heimdall

chris@ovh-dedi:~$ ls -l /opt/appdata/heimdall/
total 20
drwxr-xr-x 2 911 911 4096 Aug 16 01:05 keys
drwxr-xr-x 4 911 911 4096 Aug 16 01:05 log
drwxrwxr-x 3 911 911 4096 Aug 16 01:05 nginx
drwxr-xr-x 2 911 911 4096 Aug 16 01:05 php
drwxrwxr-x 4 911 911 4096 Aug 16 01:06 www

**What is affected by this bug?**
Heimdall is unable to be used currently

**When does this occur?**
Everytime Heimdall is installed and the program is used.

**Comment by Admin9705** [comment]
i thought this was fixed, i'll check extensively for 6.040

**Comment by Admin9705** [comment]
changed langauge as show in the picture, container is rebuilding

![image](https://user-images.githubusercontent.com/24727006/44311787-c1c62400-a3bb-11e8-8360-7a56d57f6b2d.png)

rebuilt the container and the setting is still there in a diff langauge

![image](https://user-images.githubusercontent.com/24727006/44311788-c7bc0500-a3bb-11e8-9ee5-96b878eeaa4c.png)

I rebuilt the container and settings stayed.  it was repaired not to long ago. can you upgrade to 6.039 and test.  if issues, please reopen the ticket.
