### ISSUE TITLE
Sonarr and Radarr mapping of /downloads incorrect

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#511]
as reported by astroshare here https://plexguide.com/threads/sonarr-and-radarr-containers-with-wrong-mnt-rutorrents-folder-mapping.1488/#post-9735

Both containers are mapping /downloads to /mnt/rutorrents however, rutorrent container is mapping /downloads to /mnt/rutorrent so the managers can't see the finished torrent.

**Comment by Admin9705** [comment]
https://plexguide.com/threads/sonarr-and-radarr-containers-with-wrong-mnt-rutorrents-folder-mapping.1488/#post-9781

unsure the fix is, i put what is present.  what he said is somewhat of a riddle :D any ideas

**Comment by Admin9705** [comment]
ok fixed issue: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/issues/446
