### ISSUE TITLE
PG Move w/encryption broken in 6.038+

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#516]
no option for configuring PG Move / pG drive + encryption in 6.038+

had to roll back to 6.037 for this feature to work properly

**Comment by Admin9705** [comment]
Good note, will check

**Comment by Admin9705** [comment]
did some other updates, will focus on this in 6.040

**Comment by Admin9705** [comment]
@ookla-ariel-ride did that actually work, i believed it was labeled not ready.  i'll dig back incase on an older version.

**Comment by Admin9705** [comment]
ya that's what i don't know; @Deiteq was working on it, but always had the untested label. if the move works, let me know and i can set it back in. she's out for awhile, so really unsure.

**Comment by Admin9705** [comment]
ya see the old menu

![image](https://user-images.githubusercontent.com/24727006/44316011-2783d180-a3f7-11e8-93d0-62600c3b8015.png) in 6.035

**Comment by Admin9705** [comment]
can you test this?  have to make sure encrypted works
bash /opt/plexguide/roles/pgdrivenav/encrypted.sh

**Comment by Admin9705** [comment]
Added to 6.044; tested but need more testing incase :D
