### ISSUE TITLE
Traeifk Error = Traefik 1.7 Update (From Version 6.040 and beyond)

### ISSUE THREAD

**Issue by zhdenny** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#527]
Users reporting "Error preparing server: error opening listener: listen tcp: address 8081: missing port in address" issue with Traefik on 6..040 or higher (must be related to the Traefik 1.7 update?)

I told users in Discord to deploy Traefik on any version before 6.040 and it worked for them. Just documenting here for Devs

**Comment by Admin9705** [comment]
issue resolved in 6.044 :D
