### ISSUE TITLE
docker-gc?

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#529]
can we add docker-gc to the default setup?  this cleans up all the unnecessary cruft that is not needed anymore.  containers, images and volumes that are no longer used.

see https://github.com/spotify/docker-gc

**Comment by Admin9705** [comment]
this can be added, but i won't have time for this one awhile.  i'll label it as help wanted if anyone wants to push to the project.

**Comment by WoosterInitiative** [comment]
Anyone have thoughts on using https://github.com/ClockworkSoul/docker-gc-cron instead? That way it can run every night. Thinking of combining this with a change to Watchtower that I'd like to make and would consider doing the PR if people are on board with that concept?

**Comment by Admin9705** [comment]
was added by @zachawii thanks bud!
