### ISSUE TITLE
6.045 Traefik Issues

### ISSUE THREAD

**Issue by Bluejuice1001** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#534]
Hi There,

Ok tested sonarr, radarr, sanzbd, plex working, the below programs times after deploying Traefik and TLD, it does not seem to resolve to the port set via Traefik:

TLD app set: organizrv2 . port:8040
Time out: portainer.domain.name

TLD domain: domain.name . Error "Gateway Timeout"

Your assistance would be greatly appreciated :)

**Comment by Bluejuice1001** [comment]
Hi,

Thanks did the read but never deployed WCKD. Brand new install. from 6.0.45.

Regards

**Comment by Admin9705** [comment]
disabled WCKD. some rewrites are needed.  pg5's appguard was rewritten and set in place.  please reopen ticket for any more issues :D
