### ISSUE TITLE
"Connection to rtorrent not established" error still persists on 6.048

### ISSUE THREAD

**Issue by essg88** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#539]
Describe the bug
rutorrent is displaying message "No connection to rtorrent, check if it is really running." "connection to rtorrent not established."

This is after upgrading from 6.048

To Reproduce

Go to 'serverip:8999 or rutorrent.domain.tld' have tried both. I have also tried to redeploy also

Expected behavior
rutorrent launches

Screenshots
https://imgur.com/a/STiH8Y5

What is affected by this bug?
Downloading and management of new media

When does this occur?
Whenever trying to access rutorrent. 

Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)

Operating System: Ubuntu 18.04
Plexguide Version: 6.048
Plexguide Server Type: [Remote Dedi]
Plexguide Edition: [Gdrive]
Plexguide Mount System: [Move+PGDrive]
Using Traefik: [Yes]
Domain DNS Provider:[CloudFlare]

**Comment by Admin9705** [comment]
testing, saw this work work unless they are playing with the image :D

**Comment by essg88** [comment]
Lol maybe! I'm totally unsure, I've tried to redeploy several times and through portainer do a complete removal and try to start from scratch. Are you able to reproduce the issue?

**Comment by Admin9705** [comment]
let me know if this is still a problem
