### ISSUE TITLE
Mass Backup Except Plex

### ISSUE THREAD

**Issue by jak64950** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#540]
**Describe the feature/solution you'd like**
It would be great if there could be a mass backup except for plex option. Plex never successfully backs up for me anyway so it just unnecessarily shuts my server down.

**Comment by Admin9705** [comment]
server has to shut down for the backup. that's what you have the solo option for.  to code that would is too granular.  good suggestion, but i know i it won't be done :D
