### ISSUE TITLE
gdriveclean not working with PG Move /w PGDrive (Encrypted)

### ISSUE THREAD

**Issue by kamos69** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#549]
I have a "PG Move /w PGDrive (Encrypted)" setup

I'm seeing a lot of .partial~ files for 'upgraded' episodes and movies. Last time this happened we added a fix for gcrypt in the gdriveclean.sh script. However, I noticed that recently this script has been revamped and now the problem is back.

I had a look at the gdriveclean.sh script and noticed that it checks this location `/opt/appdata/pgblitz/vars/encrypted`, if it finds stuff there it does encrypted stuff, else it does unencrypted stuff. That location doesn't exist on my server (I don't have pgblitz), I guess that's why it isn't working.

What can I do to resolve the issue? What's in this location: `/opt/appdata/pgblitz/vars/encrypted`?

**Comment by tspen** [comment]
That's a much better fix! Thanks.

**Comment by kamos69** [comment]
Was this fixed? I just did an install on a new server (encrypted) and noticed that the `/opt/appdata/pgblitz/vars/encrypted` location wasn't created.

**Comment by ogtimothymiller** [comment]
@kamos69 I don't think so. I'm having troubles with the encrypted version syncing to Google Drive as well.

**Comment by Admin9705** [comment]
pgblitz has been updated with the encryption. please reopen if this is still the case.
