### ISSUE TITLE
Solo Backup does not work.

### ISSUE THREAD

**Issue by jphermans** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#554]
**Describe the bug**
When selecting solo backup then everything will be back upped after choosing app.

**To Reproduce**
Choose solo-backup in Backup and Restore.

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu [18.04]
  * Plexguide Version: 6.0.51 [Stable]
  * Plexguide Server Type: [Remote Dedi]
  * Plexguide Edition: [Gdrive]
  * Plexguide Mount System: [PGBlitz]
  * Using Traefik: [Yes]
  * Domain DNS Provider:[Gandi]

**Comment by Admin9705** [comment]
try on 6.054. i tested the other day and worked fine.

**Comment by Admin9705** [comment]
no issues here, been using. please report any issues if this continues to occur.
