### ISSUE TITLE
nzbhydra issues with appguard

### ISSUE THREAD

**Issue by Admin9705** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#559]
https://plexguide.com/threads/cant-connect-to-nzbhydra2-jackett-anymore.1907/

**Comment by kinv** [comment]
Just to add in case you are unaware (I doubt it thought haha) also issues with the new wckd auth. connects to hydra but fails to get any nzbs. Error in logs is too many redirect requests. Seems it doesn't like having to route through wckd app then to hydra then to the nzb site lol.
