### ISSUE TITLE
disable utp for delugevpn

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#563]
I found this thread on the PIA message board regarding improving torrent performance by disabling UTP protocol https://www.privateinternetaccess.com/archive/forum/discussion/23112/anyone-having-torrent-slowdowns-please-read-this

For deluge, this requires including the ItConfig plugin.  Please consider adding this plugin to the default and disabling the UTP protocol as default.  My xfers went from 4MB/sec to 50MB/sec with this change.

here is the specific change for deluge:

(original post here https://www.privateinternetaccess.com/archive/forum/discussion/comment/45070/#Comment_45070)

For anyone using Deluge, get the ItConfig plugin and enable it. Then in Preferences > ItConfig:
- check Apply settings on startup
- check enable_incoming_utp and remove the checkmark from the Setting column
- check enable_outgoing_utp and remove the checkmark from the Setting column

Click OK. Restart Deluge (and the daemon if you're using it).

**Comment by Admin9705** [comment]
vpn removed for now - this has to be rewritten
