### ISSUE TITLE
Deluge ports are closed with Port Guard enabled

### ISSUE THREAD

**Issue by marcel5454** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#564]
Deluge is not connectable when port Guard is enabled. There should be an exception for that port. Is there any way to do so manually?

Edit: not connectable to the Torrent Network on port 58946 and therefore very slow download speeds.

**Comment by luxus** [comment]
yes all ports (exept 8112) should be open, one is for xmlrpc and the other one for connecting to the torrent network.
<img width="441" alt="screenshot 2018-10-19 at 10 36 48" src="https://user-images.githubusercontent.com/7449/47207283-25a0a500-d38b-11e8-989e-ef90c4899b30.png">

**Comment by luxus** [comment]
<img width="441" alt="screenshot 2018-10-19 at 10 55 50" src="https://user-images.githubusercontent.com/7449/47208639-a3b27b00-d38e-11e8-80bb-d972596142df.png">

it should look like this
but i think with the current way how plexguide handles port closing it's just possible to open all ports or non
i think this file apply the rule
roles/menu-ports/scripts/rebuild.sh
and its just possible to exclude containers

**Comment by Admin9705** [comment]
i know this is late but finally looking into all this.

**Comment by marcel5454** [comment]
So a quick fix I have found was to map an the port with 0.0.0.0 instead of 127.0.0.1
So change:
127.0.0.1:58946 -> 58946/tcp to 0.0.0.0:58946  -> 58946/tcp in portainer.

**Comment by Admin9705** [comment]
Just FYI, deluge will be dropped soon in PG8.  We will offer and unofficial
pgbox installer where people can submit to a community.  deluge will be put
there.
