### ISSUE TITLE
DelugeVPN Subdomain Not Accessible

### ISSUE THREAD

**Issue by DaveidWeba** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#566]
Currently, DelugeVPN's subdomain is unable to be resolved with Traefik v1.7RC, issue is resolved with using the latest stable version (v.1.6.6). I recommend setting the docker container image to **latest** instead.
![image](https://user-images.githubusercontent.com/34089153/45593491-e7f8c880-b955-11e8-95f4-9fdfb9d973ff.png)

This will solve at least two open threads
https://plexguide.com/threads/delugevpn-rtorrentvpn-not-reachable-remotely.1890/
https://plexguide.com/threads/vpn-delugevpn-error.1939/

**Comment by Admin9705** [comment]
vpn removed for now - this has to be rewritten
