### ISSUE TITLE
portainer no longer in menu to re-install

### ISSUE THREAD

**Issue by mrvaghani** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#57]
I didn't setup portainer as remote during first setup and I tried to remove and reinstall. But I realized that it is not in the menu so I am trying to figure out how to install portainer and set it up properly. Was this never in the menu? Or was it recently removed?

I also dont know which port we should be including when adding the Endpoint URL.

**Comment by Admin9705** [comment]
Goto troubleshoot on the front menu and pick the last resort reinstall. Port 9000.

**Comment by mrvaghani** [comment]
I was able to get to this screen. What do I put in the Endpoint URL? I tried my dedicated IP with port 2375 and it says "Unable to connect to Docker endpoint"

![portainer-endpoint-url](https://user-images.githubusercontent.com/7571378/32792975-b4f392bc-c932-11e7-9113-46e6060e2690.png)

**Comment by Admin9705** [comment]
Ah, leave it as local: do not select remote.  I'll put some better instructions there.  I'll put the portainer fix up for you tonight

**Comment by mrvaghani** [comment]
You are the best. I will check back after your commit and verify the menu :)

**Comment by Admin9705** [comment]
@mrvaghani, it's added to the menu now, option 11 or 12, you'll see it :D

**Comment by Admin9705** [comment]
@mrvaghani i don't blame you on the mistake, i did the same thing way back, but it's for when you run this on a local computer and have another one a remote computer and you want to connect to it. as simple as the program is, it leaves much to be desired on the start up!

**Comment by Admin9705** [comment]
@mrvaghani just for you lol, it's now part of the instructions in wiki and http://portainer.plexguide.com
