### ISSUE TITLE
pgtracker4k with traefik

### ISSUE THREAD

**Issue by kinv** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#583]
**Describe the bug**

Hi, The traefik url is wrong in setup. info on install says it should be pgtracker4k.domain.com, however in portainer it is listed as tracker.pgsuite.pw. this doesnt work because this is the same as pgtracker.

**To Reproduce**

Install pgtracker 4k
look at portainer

**Expected behavior**

pgtracker4k.pgsuite.pw

**What is affected by this bug?**

pgtracker4k

**When does this occur?**

always

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu [16.04]
  * Plexguide Version: 6.055 [Stable]
  * Plexguide Server Type: [Remote root server]
  * Plexguide Edition: [Gdrive]
  * Plexguide Mount System: [PGBlitz]
  * Using Traefik: [Yes]
  * Domain DNS Provider:[Gandi]

**Additional context**

I think this is as simple as a an oversight, should be an easy fix but what do I know. Cheers!

**Comment by Admin9705** [comment]
will do, working some optimization rewrites... so this will be easy

**Comment by kinv** [comment]
Thanks :+1:

**Comment by Admin9705** [comment]
hasn't been updated by @physk - removed from pg temp :D he's on vacation, right @physk :D
