### ISSUE TITLE
Qbittorrent pulls wrong image

### ISSUE THREAD

**Issue by kinv** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#605]
Hi, just to let you know the qbittorrent install script pulls firehol/netdata as the image and not qbittorrent. As for as I can see everything settings wise is right for qbittorent (other than wrong image) apart from when I tried to duplicate the settings and replace the image to the proper one I got some error about entry point not existing.

This is on version 6.60

Cheers +1

**Comment by Admin9705** [comment]
huh ok, checking

**Comment by Admin9705** [comment]
good catch @kinv updated in 6.063
