### ISSUE TITLE
Plex container reinstall take a very long time on a large existing Plex server

### ISSUE THREAD

**Issue by dellipse** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#606]
**Describe the bug**
When attempting to reinstall the Plex container through the PlexGuide menus it is trying to check/change permissions on the /opt/appdata/plex folder which can take an extremely long time. This step should not be necessary.

**To Reproduce**
1. Launch Plexguide
2. Choose '6.  Program Suite Installer'
3. Type 'plex' and press [ENTER]
4. Watch it remove the existing container, then wait for a VERY long time to complete the folder permissions check

**Expected behavior**
I expect it to detect an existing plex container and skip the folder creation/check step within  programs/core/main.yml lines 114-118.

**Screenshots**
N/A

**What is affected by this bug?**
Reinstallation of Plex on an existing Plex system.

**When does this occur?**
Every time I try to do this.

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.060
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: Move+PGDrive
  * Using Traefik: Yes
  * Domain DNS Provider: CloudFlare

**Logs**
N/A

**Additional context**
See https://plexguide.com/threads/6-059-hotfix-released-6-060-validation-checks.2088/post-11231

**Comment by Admin9705** [comment]
i haven't seen this issue; even on a vps that has 1 core.  but will keep this up incase of more reports.

**Comment by dellipse** [comment]
I think it might be related to the now deleted post from when 6.060 was
first released.  I bet if I let it sit for a while it would eventually
complete, but with so many objects to touch it just takes a very long time.

**Comment by Admin9705** [comment]
i haven't seen this as a problem or being reported. i'll take note incase someone mentions. please reopen if you see this to be an issue
