### ISSUE TITLE
Wrong version of containers installed when rebuilding

### ISSUE THREAD

**Issue by dellipse** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#608]
**Describe the bug**
When PlexGuide determines that it needs to rebuild the containers (i.e. after a Traefik update) it is not respecting the container choices of Sonarr/Radarr and possibly others.

**To Reproduce**
1. Launch PlexGuide
2. Choose option '3.  Traefik & TLD Deployment'
3. Choose option '2.  Deploy Traefik: Reverse Proxy' and follow the prompts
4. Allow the system to rebuild the containers
5. Determine that the wrong container is deployed using Portainer or docker to view image source.

**Expected behavior**
I expect it to rebuild the containers using the version I previously choose.

**Screenshots**
N/A

**What is affected by this bug?**
Automated rebuilding of containers

**When does this occur?**
Everytime it automatically rebuilds containers

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.060
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: Move+PGDrive
  * Using Traefik: Yes
  * Domain DNS Provider: CloudFlare

**Logs**
N/A

**Additional context**
N/A

**Comment by Admin9705** [comment]
ok good to know, will check it

**Comment by vashp2029** [comment]
Is it possible to break out the image names being pulled for each program into a separate file so we can easily modify? For example, I wanted NZBGet with MP4 Automator so I created my own Dockerfile hosted on Dockerhub (vashp2029/nzbget), and to use it, I had to modify /plexguide/programs/containers/nzbget.yml. This is fine for now, but it's likely that I'll forget about this modification after an update and it will be overwritten to the original image. Instead, if we could list override images in a separate file and have ansible watch a local directory for those, we could maintain these changes. Does that make sense?

**Comment by Admin9705** [comment]
yes an override? that sounds like a good idea.

**Comment by luxus** [comment]
an overwrite folder that checks for non-standard settings would be awesome.. it would be an advanced feature that not bother that are fine with the standard settings but would help to customize plexguide

**Comment by Admin9705** [comment]
too hard to add, but can be pushed anytime
