### ISSUE TITLE
Updated to 6.065 Broke Encrypt

### ISSUE THREAD

**Issue by qsor27** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#622]
I upgraded from several versions back and redeployed pgmove with pgdrive but now none of my media is found in /mnt/unionfs. I believe it isn't using the crypt mount I have always had in my rclone config file.

Everything functions as in file will be uploaded unencrypted its just that i'm not running encrypted anymore and it's not using the crypt mount. So I don't have any access to my TBs of encrypted media.

**To Reproduce**
Updated...?

  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.065
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: PGDrive/Move
  * Using Traefik: Yes
  * Domain DNS Provider:CloudFlare

**Comment by Admin9705** [comment]
i'll check into this, but the move and mounts haven't changed. only blitz

**Comment by qsor27** [comment]
Where should I check to make sure that it's even attempting to use my crypt mount?

**Comment by qsor27** [comment]
A3:  It will say Not Configured — if neither are present

https://plexguide.com/news/wiki/pg-move-encrypted-instructions/

This is me. Even though both gdrive and gcrypt (tdrive and tcrypt as well) are and always have been in my rclone config file.

**Comment by Admin9705** [comment]
will do, thanks for the feedback

**Comment by qsor27** [comment]
Any thoughts on how I can help figure this out? I've been looking around but I don't quite know exactly why it's not picking up on my encrypted mounts in rclone. Or any ideas on downgrading to a different version that will get me access to my encrypted media?

Thanks for your time and help!
