### ISSUE TITLE
error on changing recovery ID 

### ISSUE THREAD

**Issue by luxus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#634]
**Describe the bug**
when i try to restore from a full backup and want to change the recovery ID i got this error:
bash: /opt/plexguide/menus/backup-restore/recovery.sh: No such file or directory

**To Reproduce**
go to backup & restore
go to change recovery id

**Comment by Admin9705** [comment]
good catch, using edge? I was testing something, but reverted it. Checking!

**Comment by Admin9705** [comment]
ugh, it got merged in.  will check. thanks for the report

**Comment by Admin9705** [comment]
I'll rework it, it's not you :D

**Comment by Admin9705** [comment]
@luxus fixed on 6.074. reopen if a problem :D
