### ISSUE TITLE
Plex setup

### ISSUE THREAD

**Issue by nDiVinEx** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#64]
You mentioned to do the following

> Configuring TV Shows
> [Click] Add Library
> [Click] TV Shows
> [Type] Add Folders to Your Library: /mnt/plexdrive4/tv
> Note: You will never be able to select it; type it and hit ok
> [Click] Ok
> Configuring Movies
> 
> [Click] Add Library
> [Click] Films
> [Type] Add Folders to Your Library: /mnt/plexdrive4/movies
> Note: You will never be able to select it; type it and hit ok
> [Click] Ok

Why select /mnt/plexdrive4/tv over /unionfs/tv?

**Comment by Admin9705** [comment]
@nDiVinEx , i'll update it, those instructions were at a time where unionfs wasn't working well.  If you have any notes or updates to that setup, please feel free to update the wiki page.  Hope all is working out for you!
