### ISSUE TITLE
Not Uploading to Gdrive

### ISSUE THREAD

**Issue by resultantuk** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#65]
Installed everything using the wiki guide. Have Sonarr installed and its working with SABnzbd when i go too download a tv show it stays in the temp completed SABnzbd folder. For my settings on Sonaar i choose this dir - /yourcomputer/mnt/unionfs/tv    but nothing uploads an encrypted file to my gdrive.

**Comment by resultantuk** [comment]
Seems too have worked now... I'll check back tomorrow :)

**Comment by Admin9705** [comment]
@Deiteq will get with you on this. she's our encryption expert 🗡

**Comment by Deiteq** [comment]
Hi @resultantuk, I've been busy with getting delugevpn working so haven't run through the full install of every app yet....i'll get onto it today and test sonarr, sab and rclone crypt move settings.
Will get back to you asap!

**Comment by Deiteq** [comment]
@resultantuk , just had a look at rclone-preinstall.sh and noticed that the encrypted unionfs was pointing to /mnt/plexdrive4 instead of /mnt/gdrive.
Have corrected it now so you can give that a go if you need it working....but i'll test it all in the next couple of hours when i'm by the computer again.

**Comment by resultantuk** [comment]
Hi thanks for all the reply’s. So do I need too update anything now and if so what would I need too update. Thanks. I am abit if an new user with Linux but giving it a shot 😂👌

**Comment by resultantuk** [comment]
Should I go into the guide and delete the 3 rclone things I setup and redo them again ?

**Comment by Deiteq** [comment]
Hey, no worries...we are noobs too so learning on the job as it were!
You will first need to update plexguide by typing `plexguide` in the terminal window,
then select option `6` on the first menu to update plexguide,
then re-enter `plexguide` and select option `5`,
then try option `3` to see if anything change otherwise option `6` which should hopefully re-install the unionfs service script.

I'm just in the process of setting up rclone and plexdrive4 and after a reboot will set-up sonarr and sab to check everything is working as it should!

**Comment by resultantuk** [comment]
That’s awesome if you could also would all the directories be the same as the the guide for sonar and sab

**Comment by Deiteq** [comment]
I believe so but sonarr might need updating to reflect /unionfs/tv ignoring the zilch part as that was taken from an older version of this project....although @Admin9705 will have to confirm that.
On my sonarr i can go back a couple folders to the root directory and select unionfs from there, but I recall some people having issues seeing it so you can do the same via /yourcomputer/unionfs/tv.

Let us know if unionfs is working for you or you have any other questions!

**Comment by Deiteq** [comment]
You can always check on the move process by going back into plexguide, selecting option 5, then 5 again....this should show if there are any errors , what is being uploaded, the percentage done and how many Bytes have been transferred!

**Comment by resultantuk** [comment]
Ok so i left some stuff on DL on sonarr and now i can see some files in the crypt folder on gdrive. Seems like things are working maybe or is it possible that emby is scanning media that is actually on the VPS not in the gdrive. 

I ran the rclone test and its showing tv and text txt file. 
I also ran the unison test and it shows encypt movies(folder i made in gdrive) tv(folder i made in gdrive) and the text txt file.

Would you say that it working 👍

**Comment by Admin9705** [comment]
ya zilch was eliminted

**Comment by Deiteq** [comment]
Hmm...not sure about sonarr...possible that it takes longer to update.
If you try `ls /mnt/move/tv` it should show you a list of folders in tv....from there click arrow up key to get `ls /mnt/move/tv` again and then type in the name of the folder you want to check in....do this for each folder/directory layer until you see list of files or an empty list....if your folders have spaces in then either type \ in front of each space or even easier put the entire directory structure in `"`... 
`ls "/mnt/move/tv/tv show/season" `
If it's empty you're good.
You can also do the same for gdrive `ls "/mnt/gdrive/tv/......"`.
Check both to see if your files are in either!

**Comment by resultantuk** [comment]
Thanks @Admin9705 and @Deiteq I'll have a look soon. I think I'll have too get some more resources for the VPS first its lagging like a slug. This has been a really good learning curve.

**Comment by resultantuk** [comment]
Sorry one more thing. If i stop my VPS and start it back up what command should i use too get everything back online 👍

**Comment by Deiteq** [comment]
It should start everything automatically.
Try rebooting your server with `sudo reboot` and check!

**Comment by Deiteq** [comment]
Hey @resultantuk, 
Going to assume that everything is working so will close this issue.
Feel free to go to [http://reddit.plexguide.com/](url) if you have any other problems!

**Comment by Admin9705** [comment]
@resultantuk @Deiteq , should be fine.  Did an update, wasn't him but i believe i spoke with him on reddit just FYI

**Comment by resultantuk** [comment]
Just came back from a few day break. Been trying emby and its not the best. Everytime i install plex and i go too URL is just tells me too login and then that's it. It's like using a plex client and its not giving me and server options too set one up. Any idea?

**Comment by Admin9705** [comment]
the token may not work, you need to follow the plexguide and conduct the
ssh port foward to get to it

**Comment by resultantuk** [comment]
Thanks! that's now all done. I choose the TV dir and nothing has been added. There are empty folders of the TV shows I've added but no episodes inside them :P this has been a good learning curve i think its probably something simple maybe? 👍
