### ISSUE TITLE
Traefik Deployment does not create the service names within CloudFlare DNS

### ISSUE THREAD

**Issue by dellipse** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#653]
**Describe the bug**
The CloudFlare API calls are failing 

**To Reproduce**
1. Take any step that requires the containers to be rebuilt or Traefik to be reconfigured.
2. See error

**Expected behavior**
Services should be populated within the CloudFlare DNS automatically

**Please tell us about your environment:**
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.081 Stable
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: Move+PGDrive
  * Using Traefik: Yes
  * Domain DNS Provider: CloudFlare

**Logs**
TASK [CloudFlare Recall] ********************************************************************************************************************************************************
Tuesday 23 October 2018  13:25:04 -0400 (0:00:00.109)       0:00:20.894 *******
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No zone found with name server.domain.tld"}

**Additional context**
Since my desired DNS entries are service.server.domain.tld, I have stated that the domain is server.domain.tld instead of domain.tld.

I believe that this configuration is causing the scripts issues.  It might be good to have the script inputs as like this:

1. domain (domain.tld)
2. host/server name (servername) (optional)

This way it would still be able to access the zone for the domain AND the scripts would just need to add the server/host name prior to the service name if the field was non-empty.

**Comment by Admin9705** [comment]
dont worry, still have this on the mind.

**Comment by Admin9705** [comment]
traefik will be rebuilt in 8.5 :D
