### ISSUE TITLE
RE-Installation of Plex takes a very long time on large existing libraries

### ISSUE THREAD

**Issue by dellipse** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#654]
**Describe the bug**
When reinstalling the Plex container, the script takes the time to reapply permissions to the entire /opt/appdata/plex/database folder. This can take several minutes or hours on a large existing library due to the number of files and directories that contain metadata.

**To Reproduce**
1. Remove the plex container from an existing system with a large library
2. Reinstall the plex container from within the PlexGuide script
3. Wait a very long time for it to eventually complete

**Expected behavior**
I don't mind that it checks to see that the directory is there, and if it is not there create it. However, if it is there it should not need to chown and/or chmod the entire set of directories and files as this takes a very long time on large systems.  That function could be moved to the troubleshooting section if it is needed.

**What is affected by this bug?**
The amount of time needed to reinstall Plex. It just gets crazy long.

**When does this occur?**
Any task that reinstalls the Plex container, but not when it is just a rebuild.

**Please tell us about your environment:**
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.081 Stable
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: Move+PGDrive
  * Using Traefik: Yes
  * Domain DNS Provider: CloudFlare

**Logs**
TASK [Create plex directories] *****************************************************************************************************************************************
Tuesday 23 October 2018  16:01:44 -0400 (0:00:00.022)       0:00:01.829 *******
changed: [127.0.0.1] => (item=/opt/appdata/plex)

TASK [Launch Container Primary Information] ****************************************************************************************************************************
Tuesday 23 October 2018  16:59:11 -0400 (0:57:27.159)       0:57:28.989 *******

**Additional context**
I would have it check for the folder, but not change permissions recursively. I would move that function to a troubleshooting step with a warning that it will take a long time.

**Comment by Admin9705** [comment]
no other reports

**Comment by DaveidWeba** [comment]
Same for me actually, at "TASK [Create plex directories]" it takes 20-30 minutes for a 10GB database with 373k files. Setup was eventually proceed after the long wait, so it's not a huge deal breaker, but certainly annoying with trying to diagnose other issues.
![image](https://user-images.githubusercontent.com/34089153/48975236-28518280-f03a-11e8-8ff9-994afa20566e.png)
