### ISSUE TITLE
Namecheap traefik error

### ISSUE THREAD

**Issue by Sc4nd4l** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#655]
**Describe the bug**
Traefik does not setup properly with namecheap

**To Reproduce**
Setup traefik with namecheap. 
**Expected behavior**
Should be setup without any errors. 

**What is affected by this bug?**
Traefik configuration
**When does this occur?**
After configurating traefik with namecheap. 

**Please tell us about your environment:**
  
  * Operating System: Ubuntu 16.04
  * Plexguide Version: 6.082
  * Plexguide Server Type: Remote Dedicated
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: PGBlitz]
  * Using Traefik: Yes
  * Domain DNS Provider: NameCheap

**Logs**

**Additional context**
 
Docker traefik log: 

time="2018-10-25T21:27:40+02:00" level=error msg="Unable to obtain ACME certificate for domains \"*.domain.com\" : unable to generate a certificate for the domains [*.domain.com]: acme: Error -> One or more domains had a problem:\n[domain.com] acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Incorrect TXT record \"q-cqyxO2ncb6NHuiHmn_n7GYSRC2o27FIJHFdfAaOGQ\" found at _acme-challenge.domain.com\n",

**Comment by Admin9705** [comment]
k tracking

**Comment by AugusDogus** [comment]
:wave: @Admin9705, long time no see. Just relaunched my VPS today and I had an issue with this again as well. The solution is to edit traefik.toml and set `delayBeforeCheck = 90` instead of the default 30. Namecheap is just slightly slower than other domain providers.

**Comment by Admin9705** [comment]
that's good to know. will keep this as a note for the traefik rewrite

**Comment by Admin9705** [comment]
ya just letting you know this is stilling pending due to container rewrites still

**Comment by Admin9705** [comment]
tracking, traefik being built in 8.5
