### ISSUE TITLE
PGFork should check for sudo/root or elevate

### ISSUE THREAD

**Issue by McBeats** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#657]
PGFork doesnt seem to check for sudo/root and just throws an error when ran as a normal user.

If ansible-playbook can just be ran as sudo in the script that would work or adding something like this to the start of the script would exit with a message as well:

if [[ $EUID -ne 0 ]]; then
	echo ""
	echo "--------------------------------------------"
	echo "SYSTEM MESSAGE: PGFork not running as root!"
	echo "--------------------------------------------"
	echo ""
	echo "NOTE: PGFork must be executed as root or using ""sudo pgfork"""
	echo ""
	exit 1
fi

**Comment by Admin9705** [comment]
oh ya good one :D

**Comment by Admin9705** [comment]
need to check this

**Comment by Admin9705** [comment]
ok added!
