### ISSUE TITLE
Using rclone instead of plexdrive?

### ISSUE THREAD

**Issue by farkam135** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#67]
Saw your post on reddit about how the unionfs was using rclone instead of the plexdrive mount, I updated and was wondering why my service wasn't changing so I took a look, shouldn't the encrypted unionfs also use plexdrive instead of gdrive?
https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/blob/707546b16e8f47c02e2e3e84270884e3a0236859/scripts/docker-no/rclone-preinstall.sh#L154

**Comment by farkam135** [comment]
Scratch that, I looked deeper, /mnt/gdrive is mounted using the crypt remote which is already using plexdrive

**Comment by Admin9705** [comment]
@farkam135 , no your right. I had to update it.  The /mnt/gdrive is a mistake.  It's suppose to be plexdrive.  Conduct an update.
