### ISSUE TITLE
PG Move fails - ansible error?

### ISSUE THREAD

**Issue by gngrn1nja** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#679]
**Describe the bug**
Fresh install on Ubuntu 18.04, deploying PG Drive with PG Move fails.

**To Reproduce**

**Expected behavior**
I expected PG Drive to be deployed.

**Screenshots**
![Imgur](https://i.imgur.com/TvIl7F2.png)

**What is affected by this bug?**
Plexguide deployment.

**When does this occur?**
During initial setup.

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu [18.04]
  * Plexguide Version: 7.009
  * Plexguide Server Type: Local VPS or VM]
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: Move+PGDrive
  * Using Traefik: No
  * Domain DNS Provider: Local

**Logs**
PLAY RECAP *****************************************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   

Saturday 10 November 2018  18:58:54 +0000 (0:00:00.184)       0:00:03.437 ***** 
=============================================================================== 
Checking Existing Service Name -------------------------------------------------------------------------------------------------------------------------------------------------- 2.90s
Remove Services ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.18s
Stop If Service Is Running ------------------------------------------------------------------------------------------------------------------------------------------------------ 0.18s
ERROR! Syntax Error while loading YAML.
  expected '<document start>', but found '<block sequence start>'

The error appears to have been in '/opt/plexguide/pg.yml': line 3, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

{ role: ending, tags: ['ending'] }
- hosts: localhost
^ here

**Additional context**
Detailed explanation, related issues, suggestions how to fix, links for us to have context

**Comment by Admin9705** [comment]
good to know, will check

**Comment by Admin9705** [comment]
no other reports and had it working. reopen if an issue.
