### ISSUE TITLE
second harddrive

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#68]
when setting up the server, should i first follow these directions found here https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/wiki/Using-2nd-Harddrive

im kinda confused after this part 
my second hard drive

UUID="707cf076-5656-4b07-a062-989df6813fa3" /mnt2 ext4 defaults 0 0

save

type: mount /mnt2

sudo reboot to check

To ensure link the 2nd  back to the original

sudo rm -r /mnt/move
sudo mkdir /mnt2/move
sudo ln -s /mnt2/move /mnt/move

also, how bad is it to send tickets to whole sale internet for custom server reboots? they seem to only have custom servers for sale.

**Comment by Admin9705** [comment]
ya it's some loose instructions because i was guessing my way through, but i got it to work.  they are pretty fast for custom reboots.  So i bought a server for 40 now instead of 80.  Got a custom 250gb ssd for main and a 2TB for secondary.  You can try it.  Also dave, if you figure it out and if i have some typos, you can login and clean anything up.

**Comment by daveftw84** [comment]
how much space is your database taking?
will 250 be enough for thumbnails and transcoding/buffereing??
i just got a $104 server with 1 tb sdd and 1 tb secondary myself, tb of
fast for plex, tb of slow for snbd

**Comment by daveftw84** [comment]
the hezinter server left a bad taste in my mouth. pulling 2mb peek time, 8
mb down time.. i have too many streams at 20mb and above for that..
my sata drive was having alot of trouble keeping up with trans-coding

**Comment by Admin9705** [comment]
Well, the 1TB ssd is excessive.  My database only takes about 80gb, so there is about 140 for everything. all of the leg work is being done on the secondary 2TB drive.  Server is only running me 40.  Ya, I went from ovh > hertzer > online.net > wholesale (perfect).  Did you figure the second harddrive out?

**Comment by daveftw84** [comment]
Still being built. Custom

**Comment by Admin9705** [comment]
just follow what you can, you noticed i posted a link.  follow that instruction, i was just writing up some loose stuff.  if you are going through it and get it going, please tighten up any instructions you see.  I will close for now, but feel free to comment/reopen.  how do you like the program so far?

**Comment by daveftw84** [comment]
So far I've only used it once on my old server as an update. Everything
seems to be working great I never rebuilt it yet but it seems like addons
are broken. So I wanted to rebuild but I figured I might as well do it on a
new server. So the idea is to mount the Drive and Point Mount 1 to mount 2?
