### ISSUE TITLE
Reinstall of Traefik removes all docker containers instead of just the ones PG knows how to handle.

### ISSUE THREAD

**Issue by dellipse** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#680]
**Describe the bug**
When doing a redeploy of Traefik, all of the containers on the system are removed including those not installed or maintained by PlexGuide.

**To Reproduce**
1. Start PlexGuide
2. Select '2 - Traefik & TLD Deployment'
3. Select '5 - Deploy Traefik'
4. Watch as all containers are removed and only the ones PG knows how to handle are put back.

**Expected behavior**
The PlexGuide scripts should only manage the containers that it has installed and/or is aware of how to reinstall.

**What is affected by this bug?**
If an admin adds other software within Docker, PlexGuide removes it without warning.

**When does this occur?**
Every time Traefik is reinstalled.

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 7.009b
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: Move+PGDrive
  * Using Traefik: Yes
  * Domain DNS Provider: CloudFlare

**Comment by Admin9705** [comment]
will look into this, doing rewrites :D

**Comment by Admin9705** [comment]
using the custom containers now will stop this from messing everything up.  adding your custom container treats it as though it's part of pg

https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/wiki/Custom-Containers

**Comment by dellipse** [comment]
It would if these were just simple containers that I was in control of.
However, in my case these containers are installed by another script for a
commercial product and I doubt they would change it for our purposes.

The best thing for the PG scripts to do is to only touch the containers
that they know about and leave any other containers alone. It would be like
the company you hired to put new tires on your car decides to remove the
interior of your vehicle and not put it back when they were done. Sure, the
car might work, but it sure is a pain in the butt to sit down and drive the
thing.  ;)

**Comment by Admin9705** [comment]
ya so you can use custom containers now, but again, pg is specifically designed to be working on it's own box. conflicts and etc.  closing.
