### ISSUE TITLE
If download location is not default, report diskspace used

### ISSUE THREAD

**Issue by robertbaker** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#681]
If the download location differs, then diskspace for it should be reported as well.

Right now all diskspace reports (MOTD and when running plexguide) only reports diskspace on the first disk. Diskspace for the download location would be very useful.

**Comment by Admin9705** [comment]
yup i actually had this on the mind.

**Comment by Admin9705** [comment]
i have this halfway done. it now reports for gce, will do on next update.

![image](https://user-images.githubusercontent.com/24727006/48458246-7beae300-e793-11e8-96a2-be1818a9c8eb.png)

**Comment by Admin9705** [comment]
ignore the error and layout fixed, this was just a demo pick on hand

**Comment by Admin9705** [comment]
currently working, closing
