### ISSUE TITLE
Appguard breaks Ombi usability

### ISSUE THREAD

**Issue by binkeroni** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#684]
Appguard is requesting user/pass on Ombi when page loading, causing multiple authentication instances. Request to remove Appguard from protecting Ombi since Ombi ships with user authentication

**Comment by Admin9705** [comment]
i'm going to fix this tonight including bit warden. it's a simple fix.

**Comment by binkeroni** [comment]
Solid, thank you for your work!

**Comment by Admin9705** [comment]
I was trying to get this in last night but will focus on this now with 7.013 working. Had to make critical repairs first.

**Comment by Admin9705** [comment]
just know that this is being rewritten as part of 7.016. built a new app launcher, now cronjob. it's all in the works to align to together

**Comment by binkeroni** [comment]
Aww yeaaah! Is 7.016 dropping tonight?

**Comment by Admin9705** [comment]
fixed in 7.016, but not fully released. closing because accomplished, but if an issue on final release; please open. i rewrote everything for it :D

**Comment by binkeroni** [comment]
Aww yeahhhh! thank you again for your work!
