### ISSUE TITLE
Error while uninstalling PlexGuide on GCE Instance

### ISSUE THREAD

**Issue by pb1051** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#688]
**Describe the bug**
Error while uninstalling PG on GC instance

**To Reproduce**
1. Start PG as root
2. Choose 5 Tools and Services
3. 8 - Troubleshoot
4. 3 - Uninstall PlexGuide

**Expected behavior**
No errors

**Screenshots**
![2018-11-14_17-20-09](https://user-images.githubusercontent.com/6139274/48519179-9b384d80-e831-11e8-8f7e-b16a791cb80c.png)

**What is affected by this bug?**
Uninstall of PG

**When does this occur?**

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu [18.04]
  * Plexguide Version: 7.013 Edge
  * Plexguide Server Type: Remote GC VM
  * Plexguide Edition: GCE
  * Plexguide Mount System: [Move+PGBlitz
  * Using Traefik: [Yes
  * Domain DNS Provider: GoDaddy

**Logs**
If applicable provide the output from relevant logs and/or the output from the `pglog` command

**Additional context**
```
-----------------------------------------------------------
SYSTEM MESSAGE: Removing All PlexGuide File Directories
-----------------------------------------------------------

ERROR! Syntax Error while loading YAML.
  expected <block end>, but found '<scalar>'

The error appears to have been in '/opt/plexguide/menu/interface/uninstall/unfiles.yml': line 12, column 28, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

          - /opt/appdata/plexguide
          - {{path.stdout}}/nzbget
                           ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

**Comment by Admin9705** [comment]
got it

**Comment by haxcop** [comment]
Same issue with the latest Versions 7.2.3 +

**Comment by Admin9705** [comment]
tracking, going to fix the uninstaller; needs to be udpated

**Comment by andrewc2** [comment]
Same error trying to uninstall 8.0 too.
