### ISSUE TITLE
Flooding of error in syslog

### ISSUE THREAD

**Issue by linckez** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#69]
Hi After installing everything just as recommended on a new Ubuntu 16.04 installation, my /var/log/syslog is being flooded by this error.: 

Nov 26 15:58:32 UBUNTU-PLEX kernel: [43034.864822] audit: type=1400 audit(1511708312.309:215515): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=7790 comm="apps.plugin" requested_mask="trace" denied_mask="trace" peer="unconfined"
Nov 26 15:58:32 UBUNTU-PLEX kernel: [43034.864822] audit: type=1400 audit(1511708312.309:215516): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=7790 comm="apps.plugin" requested_mask="trace" denied_mask="trace" peer="unconfined"
Nov 26 15:58:32 UBUNTU-PLEX kernel: [43034.864823] audit: type=1400 audit(1511708312.309:215517): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=7790 comm="apps.plugin" requested_mask="trace" denied_mask="trace" peer="unconfined"
Nov 26 15:58:32 UBUNTU-PLEX kernel: [43034.864824] audit: type=1400 audit(1511708312.309:215518): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=7790 comm="apps.plugin" requested_mask="trace" denied_mask="trace" peer="unconfined

**Comment by Admin9705** [comment]
I have no idea, but will have to check later.  I never once checked syslog (which I should have).  I have made several changes since these 8 hours lol.  Please update the program.

**Comment by Admin9705** [comment]
@linckez some reading from 2014, same issue: https://github.com/moby/moby/issues/7276
