### ISSUE TITLE
Port Guard leaves portainer wide open

### ISSUE THREAD

**Issue by MarkSchmidty** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#690]
The problem: I can go to mypublicip:9000 and get an unencrypted connection to portainer, despite using everything plexguide offers for security.

My setup:
Ubuntu: 18.04
PlexGuide: 7.016b
Containers running: Plex, nzbhydra2, sonarr, radarr, netdata, blitzui, nzbget, watchtower, traefik
traefik: enabled
cloudflare: on all my subdomains and top level, including letsencrypt wildcard SSL and https rewrites. 
Port Guard: enabled 

I don't know enough about docker to workaround, since I can't fix the portainer container from portainer itself.

I have quite a few containers with "exposed" ports (e.g. sonarr on 8989, but Port Guard seems to have protected those successfully. Here's the output of netstat minus local binding:

```
root@obfuscated:~# netstat -tnlp | grep -v 127
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:32469           0.0.0.0:*               LISTEN      1047/dockerd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      901/sshd
tcp        0      0 my_pub_ip:10010         0.0.0.0:*               LISTEN      1066/docker-contain
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1047/dockerd
tcp        0      0 0.0.0.0:3005            0.0.0.0:*               LISTEN      1047/dockerd
tcp        0      0 0.0.0.0:33443           0.0.0.0:*               LISTEN      1047/dockerd
tcp        0      0 0.0.0.0:8324            0.0.0.0:*               LISTEN      1047/dockerd
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      1047/dockerd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1047/dockerd
tcp        0      0 0.0.0.0:32400           0.0.0.0:*               LISTEN      1047/dockerd
```

**Comment by Admin9705** [comment]
port guard doesnt protect portainer. it conflicts with it being turned on

**Comment by MarkSchmidty** [comment]
Appguard not protecting it is fine imo. But allowing unproxied access (e.g. cloudflare) to an http service is dangerous. (Incidentially, appguard breaks nzbget too. But it provides its own http  basic auth so it's a non-issue)

**Comment by Admin9705** [comment]
got ya.

**Comment by Admin9705** [comment]
ya traefik will go a rewrite in 7.6
