### ISSUE TITLE
pgblitz not uploading 

### ISSUE THREAD

**Issue by haxcop** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#693]
Hi guys 
recently updated to 017.b notice pgblitz does not upload the files to tdrive -
`root@theplex:/home/haxcop# bash /opt/appdata/pgblitz/upload.sh 
[PGBlitz] [Upload] Upload started for  using 
basename: missing operand
Try 'basename --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
[PGBlitz] [Upload] Moving  to GDSA folder: 
mv: missing destination file operand after '/mnt/pgblitz//'
Try 'mv --help' for more information.
[PGBlitz] [Upload]  Moved
[PGBlitz] [Upload] Uploading  to 
[PGBlitz] [Upload] Starting Upload
{
	"forgotten": [
		""
	]
}
[PGBlitz] [Upload] vfs/forgot /
[PGBlitz] [Upload] Upload complete for , Cleaning up
find: ‘/mnt/pgblitz/’: No such file or directory
^C
root@theplex:/home/haxcop# bash /opt/appdata/pgblitz/pgblitz.sh 
[PGBlitz] PGBlitz v2.1 Started
[PGBlitz] Started for the First Time - Cleaning up if from reboot
find: ‘/mnt/pgblitz/’: No such file or directory
[PGBlitz] Cleaned up - Sleeping 10 secs
[PGBlitz] BC Found! All good :)
[PGBlitz] Nothing to upload, sleeping 5 secs
[PGBlitz] Nothing to upload, sleeping 5 secs
[PGBlitz] Nothing to upload, sleeping 5 secs
[PGBlitz] Nothing to upload, sleeping 5 secs
^C
root@theplex:/home/haxcop# `

`root@theplex:/home/haxcop# ls -l /mnt/sab/complete/
total 88
drwxrwxr-x  2 haxcop lpadmin 4096 Nov  8 04:48 'American Horror Story S08E09 720p WEBRip x264-TBS-RakuvZOiDSEN'
drwxrwxr-x  2 haxcop lpadmin 4096 Nov 19 08:28 'Better Call Saul S03E05 720p WEBRip nHD x264 2-NhaNc3'
drwxrwxr-x  2 haxcop lpadmin 4096 Nov  3 02:22 'Blindspot S04E04 720p HDTV x264-AVS-RakuvZOiDSEN'
drwxrwxr-x  2 haxcop lpadmin 4096 Nov 13 04:11 'DCs Legends of Tomorrow S04E04 720p HDTV x264-SVA-Z0iDS3N'
drwxrwxr-x  2 haxcop lpadmin 4096 May 30 15:14  ebooks
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:01 'Family Guy S05E07 REAL DVDRip XviD-GoTV'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:00 'Family Guy S05E08 REAL DVDRip XviD-GoTV'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:00 'Family Guy S05E09 REAL DVDRip XviD-GoTV'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:00 'Family Guy S05E10 REAL DVDRip XviD-GoTV'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:00 'Family Guy S05E11 REALLY REAL DVDRIp XviD-FAMiLYGuY'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:02 'Family Guy S14E17 1080p WEB-DL DD5 1 H 264-CtrlHD'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:03 'Family Guy S15E03 American Gigg-olo 1080p WEB-DL DD5 1 H 264-CTRLHD'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:03 'Family Guy S15E14 The Dating Game 1080p WEB-DL DD5 1 H 264-CTRLHD'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:03 'Good Behavior S02E01 1080p WEB h264-CONVOY-postbot'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:14 'Good Behavior S02E02 MULTi 1080p HDTV x264 1-SH0W'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:07 'Good Behavior S02E03 1080p WEB h264-CONVOY-postbot'
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:30 'Good Behavior S02E04 MULTi 1080p HDTV x264 1-SH0W'
drwxrwxr-x  2 haxcop lpadmin 4096 Nov 16 05:22 'How to Get Away with Murder S05E08 720p HDTV x264-KILLERS-Z0iDS3N'
drwxrwxr-x  2 haxcop lpadmin 4096 May 30 15:14  movies
drwxrwxr-x  2 haxcop lpadmin 4096 May 30 15:14  music
drwxrwxr-x 45 haxcop lpadmin 4096 Nov 21 00:14  tv
drwxr-xr-x  2 haxcop lpadmin 4096 Nov 21 00:31 '_UNPACK_Good Behavior S02E05 720p HDTV x264-AVS-postbot'
root@theplex:/home/haxcop# ls -l /mnt/sab/complete/tv/
total 172
drwxrwxr-x 2 haxcop lpadmin 4096 Nov 20 20:34 'Black Sails S02E01 1080p BluRay x264-SHORTBREHD.1'
drwxrwxr-x 2 haxcop lpadmin 4096 Nov 20 22:49 'Family Guy S03E04 One if by Clam Two if by Sea 480p DVD x265 10bit AAC 2 0-ImE[UTR]'
drwxrwxr-x 2 haxcop lpadmin 4096 Nov 20 22:50 'Family Guy S03E05 And the Wiener is 480p DVD x265 10bit AAC 2 0-ImE[UTR]'
drwxrwxr-x 2 haxcop lpadmin 4096 Nov 20 22:50 'Family Guy S03E06 death lives dvdrip xvid-fov'
`

**Comment by Admin9705** [comment]
have you tried a test box? mine are uploading fine and your the only one not reporting. create a hetzner cloud instance or local vm.  just from one box with tons of variables, kind of hard to track.

**Comment by haxcop** [comment]
seems that the actual configuration got corrupted somehow with the pgb and gsa files, I deleted them all and reconfigure rclone and pgblitz and it's working now.
@Admin9705 Thanks for the prompt reply.

**Comment by haxcop** [comment]
Sorry @Admin9705 I might have closed this too promptly, What I'm looking now is PBGLITZ is moving the downloaded files from /mnt/sab/tv/* to /mnt/pgblitz/gdsa01/tv/* and it ends there... does not upload the file to the Team Drive.

**Comment by Admin9705** [comment]
you might have to check your keys. that's where the source of the issue is at. your the only one reporting, so you need to replicate this on a vm, hetzner cloud.  mine is continously uploading. it's the best answer i can give until those steps are taken (basically, you need to test against a baseline). reopen once tested :D

**Comment by haxcop** [comment]
Hi @Admin9705 I'm testing this on a VM which I have replicated the whole setup from start and everything seems ok until I see all the downloads remains in the folder mentioned above, now, I have also notice I'm getting this message 
`bash: /opt/plexguide/menu/interface/dlpath/main.sh: No such file or directory`
when checking opt `DL Path  | Current - /mnt ` 

Could this be related to the issue?. 
Also, my update was from 6.42 to the edge version at the time 7.16b, then I have tried 7.16f and now edge.

thanks for the support.

**Comment by DaveidWeba** [comment]
Having same issue as @haxcop, both with files not uploading with Blitz and DL Path configured as /mnt and unable to change (not sure if necessary). Currently have 1TB of data waiting to upload. Used automated setup within the Blitz menu.

![image](https://user-images.githubusercontent.com/34089153/48975108-ba0bc080-f037-11e8-845d-5279293c6fc1.png)
![image](https://user-images.githubusercontent.com/34089153/48975111-cbed6380-f037-11e8-9503-e3daaa0f882b.png)

Here's what the logs look like:
/opt/appdata/plexguide/pg.log
![image](https://user-images.githubusercontent.com/34089153/48975205-87fb5e00-f039-11e8-94fe-ea2c41958af6.png)

**Comment by the-Dakta** [comment]
I'm having the same issue https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/issues/729
