### ISSUE TITLE
Moving .inProgress directory with PGMove during plex optimize

### ISSUE THREAD

**Issue by samspade21** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#695]
**Describe the bug**
When running plex optimize, and storing the file in the same directory as the source (stored in unionfs and thus in google drive) - an interum directory is created (.inProgress) within the directory of that media.  PGMove will grab that file and begin moving it, even though it is not complete.  Files within (and including that directory) should be excluded from PGMove.

**To Reproduce**
Setup with Plex app, PGMove
1. Go to Plex and choose to optimise a piece of media.
2. Choose to store the media with the original.
3. While converting, you will see that a directory called "Media Name\Plex Versions\Version Quality\.inProgress" is created.  This is where the in progress file is being kept by default.
4. If PGMove happens to run while optimizing, the convert will fail.

**Expected behavior**
Allow the file to be created and moved by Plex automatically.  Then have PGMove move the file as intended when complete.

**What is affected by this bug?**
Users can not store optimized media with the originals for plex.

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 7.011 Stable
  * Plexguide Server Type: Local Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: Move+PGDrive
  * Using Traefik: Yes
  * Domain DNS Provider:GoDaddy

**Additional context**

Recommend adding a pgmove exclude for .inProgress/*

**Comment by Admin9705** [comment]
ya pg is not designed to use optimize and see no way for it to work with pgmove.
