### ISSUE TITLE
Docker Issue - Plex

### ISSUE THREAD

**Issue by zippy4** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#70]
Is there a way to use plex without docker because by host has an outdated Kernal which isn't supported by docker for Ubuntu 16.

**Comment by Admin9705** [comment]
Try this, it's from our nonprogrammed guide from PlexDrive 3:

https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/blob/Version-3/3%20-%20Programs%20Guide/01%20-%20Plex%20Server.md

It will install plex directly to the server, most of the v3 guide is all manual installs

**Comment by Admin9705** [comment]
@zippy4 let me know if this works
