### ISSUE TITLE
Add a service to automatically prune unused docker objects

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#702]
**Is your feature request related to a problem? Please describe.**
This isn't necessarily a problem, but I'm frustrated that unused images and volumes are being leftover whenever an upgrade is done by watchtower or otherwise. These images and volumes take up extra space that could potentially be very valuable for some people that don't have a large storage medium and have to pause their download client regularly until their disk is cleared from uploading to google drive.

**Describe the feature/solution you'd like**
I propose that similarly to how there is a prompt for backing up one's containers with a cronjob monthly, weekly, or daily, we add a prompt to ask the user if they would like the command `docker system prune` to run monthly, weekly, or daily which will

> clean up any resources — images, containers, volumes, and networks — that are dangling (not associated with a container)

**Additional context**
Please view additional resources [here](https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes).

**Comment by Admin9705** [comment]
will do, we have a command "prune" that works, but can automate later

**Comment by WoosterInitiative** [comment]
Does this not coincide with the docker-gc work that's been done?

**Comment by Admin9705** [comment]
done, in 8.0.6 

https://plexguide.com/news/changelog-8-0/
