### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

### ISSUE THREAD

**Issue by aurothic** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#71]
After sucessfully setting up rclone and plexdrive I moved on to installing plex. I entered my claim token and then selected option 2 to install plex. Upon entering 'y' to confirm the installation I receive this error.

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

```

**Comment by Admin9705** [comment]
Goto troubleshoot and click force docker install.

**Comment by Admin9705** [comment]
If all else fails, then do the start up resinstall after.

**Comment by aurothic** [comment]
This issue persists after following the above steps 1 and 2 and in addition to updating plexguide.

Could this be a problem with my vps provider? I am very new to Docker.

**Comment by zippy4** [comment]
If you're using the same VPS provider as me (AlphaRacks) Their kernel for the VPS is 2.6 which is outdated and doesn't support Docker. I'm trying to find a fix :D

**Comment by Admin9705** [comment]
@zippy4 , thanks for that. I thought I was going crazy.  Did many VM installs recently.  I never paid attention to the kernal.  Is there a certain version that it has to be on? @aurothic

**Comment by Admin9705** [comment]
@aurothic notice the reviews for the vps is bad: https://www.serchen.com/company/alpharacks-hosting/

**Comment by aurothic** [comment]
I'm currently with [SSDNodes](https://www.ssdnodes.com). I know the virtualization type affects certain things and I wasn't sure if that may be a factor with Docker. 

My VPS is currently under OpenVZ if it does carry any weight.

**Comment by Admin9705** [comment]
It might be, i ran on 3 different virtual machines today and all
installed.  Did you try the force reinstall? If not, it might be your vps.

**Comment by aurothic** [comment]
I did try to force reinstall. Do you know if OpenVZ is supported?

**Comment by aurothic** [comment]
[I have heard back from my provider](https://image.prntscr.com/image/1OUGzI9NR2We1CZC1LIWKw.png). While it appears OpenVZ is usually supported, my provider specifically uses an older kernel on their OpenVZ containers. Their newer KVM servers use the OS's kernel and should work.

Thanks @zippy4 for the insight. I thought I was going insane.

Please view this issue as closed.
