### ISSUE TITLE
REQ: Rolling CHANGELOG raw text file in root of project.

### ISSUE THREAD

**Issue by YipYup** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#713]
**Is your feature request related to a problem? Please describe.**
I hate having to go back to the forums to find the different changelog entries. I don't suggest you stop the forum thread posts, but I would like to request that the changelog is created and maintained as a MarkDown (.md) text file in the root of the project. For people who have missed daily updates, but want to see all the updates included in the versions from where they are at, to the latest version, viewing changelog in a single text file is a dream come true.

**Describe the feature/solution you'd like**
I would love for the changelog to be maintained as a raw text file, CHANGELOG.md, in the root of the GitHub project. MarkDown is a specific way of formatting the text within the text file, in such a way that it is both (1) easy to view when edited as raw text and (2) easy to view when viewed through a website; there is wide support for markdown-to-HTML automated rendering, such as GitHub themselves do.

Here's an example of a changelog file written in MarkDown. You can see how while it is the same single file, accessing it via one that uses MarkDown so that it is formatted pretty when viewed on GitHub.com, but also visually appealing when viewed as raw text:

- Rendered as HTML: https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md
- Rendered as raw: https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/master/CHANGELOG.md

Another example of one changelog file, but not in markdown. This one is just to show you actual content where the project maintainers do numbering the software version, the date it was released, and notes about the changes made between versions :
https://download.configserver.com/csf/changelog.txt

**Comment by Admin9705** [comment]
ya i did this in the past, but only will continue to use site. i understand it's purpose, reasoning and appreciate the suggestion.  the site enables to use pics and easily drop movie clips and etc and the md format is both easy and a pain.  for now, i'll keep it as is.
