### ISSUE TITLE
/mnt/move/abooks needs permissions set

### ISSUE THREAD

**Issue by robertbaker** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#718]
LazyLibrarian uses ebooks for ebooks and abooks for audiobooks.

Currently the PG installer does not set permissions for abooks under the move directory.

The PG installer needs to add permissions to abooks, same as it does right now with ebooks.

**Comment by Admin9705** [comment]
ok easy to do

**Comment by Admin9705** [comment]
i think u resolved this @robertbaker ?
