### ISSUE TITLE
CLAIM Plex Server - Does not work

### ISSUE THREAD

**Issue by aurothic** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#72]
This functionality did not work. Reporting this behavior as instructed.

**Comment by aurothic** [comment]
After attempting this method, when tunneling to my server and attempting to claim my server I am only shown a popup advert about Plex Pass. I am unable to claim my server.

**Comment by aurothic** [comment]
Reinstalled my VM and just tried plexguide with a fresh install. Now realized that using the plex claim token is forced I tried this method to have [the same result](http://prntscr.com/hghdmp).

**Comment by Deiteq** [comment]
Hey @aurothic,
Have you tried using the FreeNom method in the wiki guides? 
I noticed that the plextoken wasn't moving to preferences.xml but was able to access my server with the domain name.
Try that and see how you get on, I'm currently trying to figure out how to get the plextoken to work in the meantime.

**Comment by aurothic** [comment]
I just ugpraded my VPS today and my domain is still propagating through the DNS servers, but I will make sure to try this soon.

Note: This issue persists when launching plex through [Plex.tv](http://app.plex.tv), and through the VPS' IP XXX.225.219.XXX:32400/web.

**Comment by aurothic** [comment]
Is there a workaround I can use, perhaps manually editing the preferences.xml file?

**Comment by Deiteq** [comment]
I think it's because all the containers are within their own network, on my test vm I had to use the ip address shown on portainer to access plex instead of the vm's actually ip....not sure if that helps at all?
We're still new to this so trying to figure it out as and when we hit hurdles!

**Comment by aurothic** [comment]
Is there a way I can access this ip address outside the network through tunneling or another means?

**Comment by Deiteq** [comment]
Not sure what would be best, you might be able to go into portainer and temporarily change the network to Host or Bridged to see if that works, then set it back to normal after claiming your server.  
Did you try using the free domain settings in the wiki guide?
Otherwise @Admin9705 might be able to help when he's back online.

**Comment by aurothic** [comment]
No I did not try using the free domain settings as I've had my paid domain for over a year, but as I mentioned I upgraded my VPS today and was assigned a new IP address and had to update the DNS records with my domain provider. I don't see why I should try the free domain option as it will take just as long for the changes to propagate.

**Comment by Deiteq** [comment]
I just thought that maybe you can do a quick temp one just so you can claim the server, mine was pretty much instant!

Sorry I can't be of much help, it's late here so going to bed now, if @Admin9705 can't help tonight then I'll be back on tomorrow trying to find a way to get the tokens working.
Take care!

**Comment by Admin9705** [comment]
@aurothic , i'll remove the token shortly.  We needed some feedback, i really wished it worked :(  Thank you for being super proactive on this!  Me and Deiteq conducts 100's of VM resets and snapshots to get this right!

**Comment by Admin9705** [comment]
@aurothic @Deiteq , blocked out the claim server.  @Deiteq , there is a hidden option for #4 to utilize the tocken for testing, making a hidden option 5 & 6 for beta ymls for the token :D

**Comment by aurothic** [comment]
Thanks @Admin9705! I'll give it a go now! It would be nice if a user could enable different logging levels for debugging with the default being none.

**Comment by Admin9705** [comment]
ya it's just building the logs, I don't know where it would output it and etc :D Honestly, i've been using linux for 5 months and that's it lol!

**Comment by Admin9705** [comment]
@aurothic one sec, i see why plexdrive wasn't working, so i moved part of the code to the preinstall, but forgot to make it say yes, install mongodb

**Comment by aurothic** [comment]
Uh Oh, Plexdrive is working just fine for me so I'm not sure what you're talking about. Maybe you're referring to a different issue?

**Comment by Admin9705** [comment]
grr.. stupid plex menu not working, give me a sec :D

**Comment by Admin9705** [comment]
@aurothic ok menu fix, plexcontainers fixed to install directly.  If you find any other issues, please let us know!  We are trying to stablize version 4.  Once it's stablized with all the programs installed, it will be a version that remains consistent for a while and will create v5 as a developer. V4 is the first programmed one, where as 3 was all you typing crap in manually.

**Comment by aurothic** [comment]
Not sure where you're seeing an issue with plexdrive4, it is working fine for me. Glad to hear about progress updates though.

**Comment by aurothic** [comment]
Now I can no longer install Plex. When selecting 1 on the menu of programs to install nothing happens and I'm stuck at the same screen.

**Comment by Admin9705** [comment]
@aurothic , ya so update again, it works now. gotta love the fast update option lol :D

**Comment by aurothic** [comment]
Thanks, retrying now!

**Comment by aurothic** [comment]
Hm. I'm still unable to claim my server, but this issue does not appear to be with the title. Please view this issue as closed.
