### ISSUE TITLE
PG System & Network Auditor Exit option listed as [4] instead of [z]

### ISSUE THREAD

**Issue by Neomoon** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#721]
**Describe the bug**
When in the PG System & Network Auditor menu the exit option is incorrectly listed as [4]
**To Reproduce**
1. Go to PG System & Network Auditor
2. Type 4
3. Hit Enter
4. ERROR - Bad Input! | Press [ENTER]  message displayed
5. Type z
6. Hit Enter
7. Menu correctly exits back to PG Tools Interface Menu

**Expected behavior**
Menu should list [Z] as option to Exit not [4]

**Screenshots**
If applicable, add screenshots and/or .gif to help explain your problem.

**What is affected by this bug?**
Menu UI

**Comment by Admin9705** [comment]
ah thanks, keep forgetting will patch tonight for minor updates i want to do, just visual changes.

**Comment by Neomoon** [comment]
Glad to help :)

**Comment by Admin9705** [comment]
fixed in 7.4.13 and 7.5.0
