### ISSUE TITLE
Allows by a easy way to import a rclone.conf file for who have already used encrypt!

### ISSUE THREAD

**Issue by ruCyberPoison** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#726]
**Is your feature request related to a problem? Please describe.**
Yes, this don't allow to uncrypt a tdrive allready encrypted per 1 account. So this can be better to be emplemented in (PGBlitz) to just set a path and the PGBlitz allow easily to "grab" the rclone.conf made by the user "Made by hands"

**Describe the feature/solution you'd like**
When someone select a path location the PGBlitz grab the .conf file done previously and don't change any things (password=, password2=,...) i have tried to do that manually but the PGBlitz change the password= and password2= so the gdsac users can't decrypt the content in the drive team, and i think many people like me prefer to be able to do some configs manually and able to edit/change/add some configs by her hands (May be more for people with a little rclone experience ). 

**Additional context**
To this exemple i have one config file than actually it's like this,

```Bash
[Google Drive Storage 1]
type = drive
client_id = ********CLIENT*******
client_secret = ******SECRET******
scope = drive
root_folder_id = 
service_account_file = 
token = *******TOKEN*******
team_drive = *********IDRIVETEAM******

[Plex Cache]
type = cache
remote = Google Drive Storage 1:/
plex_url = http://127.0.0.1:32400
plex_username = my@email.com
plex_password = manynumbersandcharacters
chunk_size = 10M
info_age = 72h
plex_token = blablabla...exemple
chunk_total_size = 500G
db_path = /mnt/Plex\ cache/
chunk_path = /mnt/Plex\ cache/
chunk_clean_interval = 15m0s
tmp_upload_path = /mnt/tmp_upload/tmp
tmp_wait_time = 1h
write = true

[gdcrypt]
type = crypt
remote = Plex Cache:
filename_encryption = standard
directory_name_encryption = true
password = ****PASSWORD****
password2 = ****PASSWORD2****

```

And this is how my tree looks like in my /mnt/

```bash
root@dragonight:/mnt# tree
.
├── CloudStorage Server 1
│   ├── 3sbg40mejn1kb8naaibudv4m0g
│   ├── 4g8cafcuj5peslj259b15pmdlk
│   ├── 4ojqj4usrfq7ip9v3bmgtr4ap0
│   ├── 77q5qsu125n3tlreotqu7jqe30
│   ├── 9vojgd4vee8dc855tcid748kjg
│   ├── b0kfkh4acjooopr90a56i0lfps
│   ├── df4cl9uit4c3179arrlvc1od70
│   ├── oeoc6utr79p9o7oq21k55gu8ls
│   └── vl2q1fivfe3dnlr31gv00vr138
├── Cloud Storage Server 1[UN]
│   ├── EN
│   │   ├── floodrt[EN]
│   │   ├── Movies[EN]
│   │   ├── Organize[EN]
│   │   └── TVShows[EN]
│   ├── FR
│   │   ├── Films[FR]
│   │   ├── floodrt[FR]
│   │   ├── Organize[FR]
│   │   └── Series[FR]
│   ├── Twitch Replay
│   └── Youtube
├── Plex cache
└── tmp_upload
    └── tmp

26 directories, 0 files
```

Whre UN = Uncrypted,

So when i tree the mnt now it's looks like somethings like 

```
├── move
│   ├── movies
│   ├── music
│   └── tv
├── nzbget
│   ├── completed
│   │   ├── ebooks
│   │   ├── movies
│   │   ├── music
│   │   └── tv
│   ├── incomplete
│   ├── log
│   ├── nzb
│   ├── queue
│   └── tmp
├── pgblitz
│   ├── gdsa01
│   ├── gdsa02
│   ├── gdsa03
│   ├── gdsa04
│   ├── gdsa05
│   ├── gdsa06
│   ├── gdsa07
│   ├── gdsa08
│   ├── gdsa09
│   ├── gdsa10
│   ├── gdsa11
│   ├── gdsa12
│   ├── gdsa13
│   ├── gdsa14
│   ├── gdsa15
│   ├── gdsa16
│   ├── gdsa17
│   ├── gdsa18
│   ├── gdsa19
│   └── gdsa20
├── pgops
├── Plex cache
│   └── tmp
├── plexdrive
├── portainer
├── pyload
├── qbittorrent
│   └── downloads
│       └── incomplete
├── rutorrent
│   └── downloads
├── sab
│   ├── admin
│   ├── complete
│   │   ├── ebooks
│   │   ├── movies
│   │   ├── music
│   │   └── tv
│   ├── incomplete
│   └── nzb
├── tcrypt
```
And many more, why not just one folder in mnt like /mnt/plexdrive

and let useres to chove the mnt folder (Name, or one already created)  to send data over pgblitz ?

**NOTE** i taked this part of the tree above because as you can see the gdsaxx is not working but with my configs as before with configured only tdrive/tcrypt/gdrive/gcrypt (See first tree) it's working.

Issues created in the forum ==>[https://plexguide.com/threads/pgblitz-sh-gives-error-and-sunionfs-fails.2850/](https://plexguide.com/threads/pgblitz-sh-gives-error-and-sunionfs-fails.2850/)

I also would like to know if there is a way to start pgblitz like a normal [rclone mount] 
to be able to start the pgblitz like i have done in the past !

```
rclone mount Google\ Drive\ Storage\ 1:/ /mnt/CloudStorage\ Server\ 1/ --vfs-cache-mode full --allow-other --dir-cache-time 1h --tpslimit 25 --tpslimit-burst 25 --transfers=500 --daemon --umask 002 --bind public.ip.v4.darpa --allow-non-empty --log-level INFO --log-file /home/logs/rclone.log

rclone mount gdcrypt: /mnt/Cloud\ Storage\ Server\ 1[UN]/ --umask 002 --checksum --allow-other --fast-list --tpslimit 25 --tpslimit-burst 25 --dir-cache-time 1h --transfers=500 --daemon --vfs-cache-mode full --log-file=/home/logs/rclone.log --log-level ERROR&

```

This is what i have used in the past for rclone but i received that issue of Transfer Rate exeded so i would like to use PGBlitz but with my (password, password2 . Encryption password ) 

public.ip.v4.darpa = is a exemple to don't have to show the ipv4 public to everyone
Have a good day,
ruCyberPoison

**Comment by Admin9705** [comment]
good info, i'll check into this

**Comment by Admin9705** [comment]
https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/wiki/RClone-Manual-Deploy

this is what users have to do now.
