### ISSUE TITLE
Add more customization for watchtower settings

### ISSUE THREAD

**Issue by WoosterInitiative** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#727]
**Is your feature request related to a problem? Please describe.**
I have started to add my own docker containers outside of PlexGuide and they don't necessarily make sense to include (e.g. [Home Assistant](https://home-assistant.io/ "Home Assistant Homepage")). I WOULD like to be able to have watchtower watch those extra containers, but the current setup doesn't make that easy.

**Describe the feature/solution you'd like**
Customization per package similar to old backup scheme with a global option if desired.

**Additional context**
watchtower allows for labels to be used similar to Traefik to control which containers are updated. That way containers outside the PlexGuide umbrella can take advantage of it. That's how I'm getting Traefik to do it now.

**Comment by Admin9705** [comment]
ya either you have to enable it or not use it. if not used, you'll have to update.  i know for with all the things going on, i won't have the time to grain it down (when there is no such demand for it). but will do so one day once all major tasks are accomplished
