### ISSUE TITLE
Unable to claim Plex server.

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#74]
After using ssh -L 32400:ipv4address:32400 root@ipv4address and navigating to http://localhost:32400 I am prompted to purchase plex pass and the sidebar's refresh wheel continuously loads and does not find a server.

I've installed Plex around a half-dozen times before and never experienced this issue.

**Comment by Admin9705** [comment]
i'll test myself about goin in.  I always used terminal from windows. the
linux portion is rewritten by @Detique

**Comment by aurothic** [comment]
I've previously setup Plex using this method. I've used Putty previously as well, but am currently on a OSX machine or I would do so again.

**Comment by Admin9705** [comment]
ya i'll have to check with her. i'm working betas to get that token up and
running. there is very poor documentation on how to implement it.

**Comment by aurothic** [comment]
Is there an alternative or workaround you can suggest currently? The ssh tunnel should be correct as I'm able to visit localhost:32400 in my browser and view Plex. Would it be ill-advised to manually install Plex at this time?

**Comment by Admin9705** [comment]
you could, except you have to update it which is not hard. click version 3 guide and you can install plex easily. i do apolgize about the ssh piece for mac, which i have not done personally.  i'll work hard this week to get that token fixed :D

**Comment by aurothic** [comment]
Thanks! There's a really simple method of updating Plex done with a script that I've used in the past and worked flawlessly that you can find [here](https://github.com/mrworf/plexupdate).

**Comment by aurothic** [comment]
Using the tool I linked in [the above comment](https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/issues/74#issuecomment-347734319) I successfully installed Plex and validated that the issue lies with PlexGuide's implementation of Plex.

**Comment by Admin9705** [comment]
hey that's great. i'll check it and maybe we can implement :D

**Comment by Admin9705** [comment]
@Deiteq heading to bed, but if you have time to check it: https://github.com/mrworf/plexupdate

@aurothic , how did you use it mostly? again, thanks for working with us.

**Comment by Deiteq** [comment]
Hey guys!
Yeah I used mr.wolf's method in the past too, so easy to do now.
i think the problem with the plexpublic install could've been down to the token only working with plexpass users, we should've just had the token part for the plexpass install not public.
But even so I was still having issues with the token getting implemented so was looking at using linuxserver's plex docker to see if that makes it easier!

I have a fresh remote server to work on today and will see how that goes with the docker containers being in their own ip network.

**Comment by aurothic** [comment]
@Deiteq were you able to make any progress on resolving this issue?

**Comment by M96268004** [comment]
@Admin9705 try ssh username@ipaddress -L 32400:localhost:32400
than access via http://127.0.0.1:32400/web

**Comment by Admin9705** [comment]
@M96268004 , we have that in the guides, i'll make sure the formatting you have matches :D

**Comment by Deiteq** [comment]
@aurothic , sorry for the late reply....got side tracked!
actually got something in the beta section that i'm working on and i think it's working, if you would like to check it out then it's named TestPlex under option 8.
only plexpass holders need to provide a claim token.
i tested it on my remote and a vm late last night and it's looks like it's doing the job of claiming the server.

i haven't had any time to look into mr wolf's auto updater though, but assume that you won't need it with docker anyway.

**Comment by Admin9705** [comment]
@Deiteq once it's all set, we'll bake in have the wording set :D

**Comment by da-vaz** [comment]
Has this been resolved with the latest pushes? I'm having the same issue.

**Comment by Deiteq** [comment]
Hey @da-vaz, it's still in beta if you wanna give it a go...I think it's fixed....but too tired to give it another run through with a vm tonight....hope to do it tomorrow though.

**Comment by TheCreatorzOne** [comment]
Since Plex Server claiming with tokens has officially been implemented i will be closing this... To claim the server, just reinstall through the menu...

**Comment by AugusDogus** [comment]
@TheCreatorzOne please reopen this issue. I attempted the implementation with no success.

**Comment by TheCreatorzOne** [comment]
Okay, what appears to be the problem and are there any logs or errors?

**Comment by Admin9705** [comment]
He said it's good now :D
