### ISSUE TITLE
Sab has been downloading to appdata

### ISSUE THREAD

**Issue by robertbaker** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#741]
I reinstalled sab with the latest 7.6edge and sab downloads to /opt/appdata!

Using linuxserver image

**Comment by Admin9705** [comment]
hmm really? can u send a screenshot. u can copy and paste here.

**Comment by robertbaker** [comment]
Everything, it's odd. I deleted the folder from appdata and it starts dumping everything in there.

**Comment by robertbaker** [comment]
It's because downloads are under /config now??

 - "/opt/appdata/sabnzbd/:/config/"
        - "{{path.stdout}}/sab/downloads:/config/Downloads"

So its basically a race condition if this works or not. Why was the download paths changed?

I would have changed them to be a bit more standardized something like /downloads/sabnzbd/complete

Then in radarr, etc you do the same.

You also mount to /mnt/sab but /mnt/sabnzbd is created and empty.

The dl paths for the all downloaders and pvrs need redone

**Comment by TechButton** [comment]
I can also confirm with the new version I am also seeing issues on SAB and Radarr talking to each other. Radarr can see the movies that downloaded but they will not auto move anymore. I am working through the problem and see if I can find a solution currently.

**Comment by TechButton** [comment]
I did see there is now a temp directory that it is trying to download to first and then move to the other /config/downloads. I removed that temp folder right away, and didn't verify that was an issue. I will back up my sabnzbd and redeploy it again and try it out.

**Comment by robertbaker** [comment]
The downloads must be moved out of /config

Having it like this causes weirdness with docker and it's.not.predictable. Sadly I just losty queues of 1tb of completed files. I'll have to rename and move normally.

The linuxserver dockerfile exposes volumes that differ

**Comment by robertbaker** [comment]
Also lazylibrarian was never updated with the new paths.

I would do a find/replace searching the entire project next time to be safer.

**Comment by Admin9705** [comment]
sorry guys, will check into this, working something else. if you want to push things, please do :D working on a traefik google oauth solution

**Comment by robertbaker** [comment]
I should be able to help fix this tomorrow but I think we should fix all the paths once and for all. We should avoid mounting a parent and a subfolder in the mounted parent as things get goofy.

Also enable that oauth by default for blitzui

**Comment by Admin9705** [comment]
@robertbaker sounds good, just push to 7.6 if u can.  7.7 is experimental with traefik right now.  once it's 15 jan, i'll remove Edge and default the working project as in it would 7.6 now if it was the case.  Thanks for your help and mentorship along the way. studying traefik more now, i see what you really did.  i'm studying the backend piece along with the expose port.  goal is to get the plex subdomain working.  the authentication piece is working well, just held up by one piece.

**Comment by robertbaker** [comment]
This is what I'm thinking, this will be completely breaking but a script should be able to mv the old structure and adjust the config files.-

containers & app configs:

/downloads/incomplete/nzbget aka /downloads/incomplete/{{pgrole}}
/downloads/nzbget
/incomplete/sabnzbd
/downloads/sabnzbd
/incomplete/qbittorrent
/downloads/qbittorrent
[...]

instead of /mnt/sab,/mnt/nzbget....

/mnt/incomplete/nzbget 
/mnt/downloads/nzbget 
/mnt/incomplete/sabnzbd
/mnt/downloads/sabnzbd
/mnt/incomplete/qbittorrent
/mnt/downloads/qbittorrent
[...]


This accomplishes a few things.

* Easy extendable pattern to support more downloaders and stuff in the future.
* Allows  a consolidated location that can be used for search/import/browsing, for example I could run
`du -h /mnt/downloads` to get a print out of sizes for all of my downloaders.

**Comment by robertbaker** [comment]
Just tested and sab and deluge are both working again for me.

The issue is with the downloaders and the PVRS the paths have to match on both sides of the mapping and they all must match each other or it doesn't work. When sab was changed to /config/Downloads, it no longer matched the left side and broke.

sonarr and the rest of the downloaders should work again now too.

**Comment by Admin9705** [comment]
resolved with updates
