### ISSUE TITLE
rename pgrole for hydra, organizr, and (maybe) sonarrbeta

### ISSUE THREAD

**Issue by robertbaker** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#742]
Let's remove versions from hydra2, the pgroles should match the project name, unabbreviated. The config and mnt folders should match.

**Comment by robertbaker** [comment]
organizrv1 is dead.

hydra1 is dead

I've had no problems with Sonarrbeta, anyone mind if that was the only option (get rid of old version)

**Comment by Admin9705** [comment]
sounds good!

**Comment by robertbaker** [comment]
I didn't do this yet for sonarrbeta, I decided to wait a bit as that would force every one to upgrade. I think most are on hydra2 and orgv2
