### ISSUE TITLE
override subdomain name

### ISSUE THREAD

**Issue by robertbaker** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#743]
During install, it would be nice to ask to override the subdomain, for example. I rather not tell the world I'm hosting sabnzbd on my domain. I would like the option to change it to whatever I wanted. This would just be for the subdomain only, the traefik name should still remain the role name.

**Comment by Admin9705** [comment]
that can be an addition within 7.7

**Comment by Admin9705** [comment]
closing this, i put on the idea board, but insanely complex with very little demand.
