### ISSUE TITLE
provide OTB default configs where apps are connected if feasable

### ISSUE THREAD

**Issue by robertbaker** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#744]
To ease setup and reduce configuration, I think it would be a good idea to expand the configuration plexguide does during install for radarr/sonarr/etc. We can provide OTB configs where the downloaders are setup and connected (but disabled).

for example, on radarr install we can set up jackett, nzbhydra, sab, nzbget, deluge,qbittorrent,rtorrent,etc,etc. Then users just need to chanage the api keys, usernames and passwords.

Of course this is easier for text configs and less for the db files of sonarr/radarr. This would only happen on clean install, non-overwrite.

A bit of work initially but big payoff.

**Comment by Admin9705** [comment]
Sure sounds like a plan! Got the Google oauth piece done so baking in.

**Comment by robertbaker** [comment]
Closed with 8.1 beta. Need find sln for radarr/sonarr
