### ISSUE TITLE
PGFork, PGEdge broken w/ new installer

### ISSUE THREAD

**Issue by robertbaker** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#745]

**Comment by Admin9705** [comment]
oh yeah good catch, i'll do an update on 7.6 to repair pgfork.  pgedge is no longer a used option.

**Comment by Admin9705** [comment]
k 7.6.12 released; pgfork is fixed.  just update; run plex and give it about a minute. commands update in the background.
