### ISSUE TITLE
PlexInTheCloud Ideas

### ISSUE THREAD

**Issue by Admin9705** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#75]
https://github.com/chrisanthropic/PlexInTheCloud

Observing any useful features to improve plexguide @Deiteq

**Comment by resultantuk** [comment]
https://github.com/Digiex/M4V-Converter
This could be an idea ?

**Comment by Admin9705** [comment]
it will also be worth adding @resultantuk

**Comment by AugusDogus** [comment]
[Mylar & Ubooquity
](https://www.reddit.com/r/AwesomePlex/comments/7g727y/future_support_of_mylarubooquity/)

**Comment by Admin9705** [comment]
@AugusDogus , yes sir tracking :D
