### ISSUE TITLE
Updating to the latest version while on an old version re-installs everything over again.

### ISSUE THREAD

**Issue by Rothuith** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#77]
Updated to the latest version just to install NZBGet, noticed the installer doesn't ask and "pre-installs" everything.

I didn't lose any of my config but it was pretty scary.

Might make it to ask if you're updating or installing the program for the first time as an option.

**Comment by Deiteq** [comment]
Hey @Rothuith,
I think all your settings get saved outside of /opt/plexguide and in /opt/appdata, so it should be safe!

**Comment by Admin9705** [comment]
@Rothuith they get save in /opt/plexguide, so your good!
