### ISSUE TITLE
PG8 install

### ISSUE THREAD

**Issue by Kongledyret** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#772]
**Describe the bug**
Fresh install of v8 fails

**To Reproduce**
Install V8 on a clean box. 

**Expected behavior**
Should install as normal 

**What is affected by this bug?**
Fresh install of 16.04 
**When does this occur?**
When installing v8 on a fresh box running 16.04 
**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 16.04
  * Plexguide Version: 8 Stable
  * Plexguide Server Type: Remote Dedi

**Logs**
Cloning into '/opt/pgstage'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 179 (delta 11), reused 0 (delta 0), pack-reused 155
Receiving objects: 100% (179/179), 43.11 KiB | 0 bytes/s, done.
Resolving deltas: 100% (87/87), done.
Checking connectivity... done.
sh: 55: ansible-playbook: not found
cp: cannot stat '/opt/plexguide/menu/alias/templates/plexguide': No such file or directory

**Comment by Admin9705** [comment]
ok will check

**Comment by Admin9705** [comment]
![image](https://user-images.githubusercontent.com/24727006/50726492-d5102c80-10db-11e9-902a-507c56be000e.png)

**Comment by Admin9705** [comment]
![image](https://user-images.githubusercontent.com/24727006/50726597-9e3b1600-10dd-11e9-8c86-f28a59cac704.png)

**Comment by Admin9705** [comment]
works fine in 16.04. might be something up with the box. It has something do with your remote server.  Please reopen ticket when you discover the issue.
