### ISSUE TITLE
Add Deluge as a Docker Container as a default program to install.

### ISSUE THREAD

**Issue by Rothuith** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#78]
The Automatic Installer doesn't have any torrent installer. Deluge is a nice and easy one to deploy with docker.

**Comment by Deiteq** [comment]
Hey @Rothuith,
I am actually in the process of doing that but to run through pia vpn, I hope to have it fixed this week!
Keep your fingers and toes crossed!

**Comment by Admin9705** [comment]
In addition, we'll add a non-vpn version, be a selection. @Deiteq  has been working hard on it :D

**Comment by Deiteq** [comment]
@Rothuith, 
I've got **delugevpn** working internally so if you tunnel in or are using a desktop environment then it'll work but not quite for remote server access...yet!
If you wanna test it in your own vm environment then go to **beta** section and select **delugevpn**, but you will need a **pia** vpn account first!
Plus don't forget to update **plexguide** beforehand!

**Comment by Rothuith** [comment]
But why run it as a VPN if everything else is running behind the NGINX reverse proxy?

A bit confused.

**Comment by Deiteq** [comment]
I think VPN is more secure especially for torrents as everything will be encrypted.
I couldn't tell you the differences as I'm a noob too...so learning on the job....all I know is that it's best to run torrents through a VPN to cover yourself.

**Comment by Admin9705** [comment]
ya the proxy server doesn't protect you @Rothuith for torrent downloads. a vpn is what encrypts your traffic. the reverse proxy is what protects your internal security of the server.

**Comment by AugusDogus** [comment]
It would be nice to see the [OpenVPN](http://forum.deluge-torrent.org/viewtopic.php?t=49883) standard adopted instead of restricting users to PIA.

**Comment by Admin9705** [comment]
@AugusDogus , it's somewhat hard to implement.  If you come across a good solution to build in, we'll take it :D

**Comment by AugusDogus** [comment]
I stumbled across this [OpenVPN client docker container](https://github.com/dperson/openvpn-client) that describes itself as being 

> designed to be started first to provide a connection to other containers (using --net=container:vpn)

Perhaps this is an easy solution.

**Comment by AugusDogus** [comment]
Here is [another resource](https://www.reddit.com/r/docker/comments/3w0498/docker_containers_routed_through_openvpn_client/) for someone using deluge through the same openvpn docker container mentioned above.

**Comment by Deiteq** [comment]
Hey guys,
Just reading through binhex's delugevpn forum to try to find a solution I'm on page 9 of 104 so may take a while longer!
I'm just trying to figure out why it's not working with plexguide, it works fine locally, just not remotely....I'm very new to docker world....so it'll be a steep learning curve for me!

**Comment by Admin9705** [comment]
Yes it is!

**Comment by Admin9705** [comment]
@Rothuith @AugusDogus , it's in the menu now, kind of getting it worked out. need an iptorrent invite

**Comment by Admin9705** [comment]
Done, now we need help with it
