### ISSUE TITLE
/mnt/unionfs not being created in 8.1.beta1

### ISSUE THREAD

**Issue by sammykins12** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#786]
**Describe the bug**
In 8.1.beta1 the UnionFS install service fails to create and hence does not allow it to properly create the UnionFS mounts as it should.

**To Reproduce**
- Attempt to deploy a PGMove service
- Recieve error in deploy logs as below

**Expected behavior**
The /mnt/unionfs should be created and union between /mnt/move and /mnt/gdrive

**What is affected by this bug?**

Installation of UnionFS Service in the PGClone deployment

**When does this occur?**
When deploying a PGClone service

**Logs**
```
TASK [Install UNIONFS Service] **************************************************************************************************************************************************
Thursday 10 January 2019  12:01:19 +1030 (0:00:00.286)       0:00:00.360 ****** 
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'unionfs_path' is undefined"}
    to retry, use: --limit @/opt/plexguide/menu/pgclone/munionfs.retry

PLAY RECAP **********************************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=1  
```

**Additional context**
https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/commit/95c235b41f14e8a015ba323abf6c195751b04e48?diff=split is where the issue stems from, I deleted the changed line and replaced it with the older version

**Comment by Admin9705** [comment]
we fixed it!
