### ISSUE TITLE
Support for custom named folders & other folders

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#79]
I currently have my google drive laid out like [this](http://prntscr.com/hinynk). I'd like support to enter in a folder name for plexguide to use.

When running the unionfs test I don't see these folders, but I do see 'movies	tv  uniontest.txt'.

Because I have separate folders for Anime, TV Shows, and even Cartoons I'd appreciate the ability to add libraries to plexguide.

**Comment by Admin9705** [comment]
This feature will not be supported.  Basically, you will have to create the folders, match them in plex, and use sonnar and radarr to adjust to folders accordingly.  This can be done custom wise, but not feasible for programming it / with time and effort.  This is just a get it and go script.

**Comment by AugusDogus** [comment]
Understandable. Thanks for you input.
