### ISSUE TITLE
Unionfs not working

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#80]
When attempting to import tv shows into Sonarr from `/unionfs/tv` nothing appears and when troubleshooting I see `movies	tv  uniontest.txt`, but none of my other folders. 

Before renaming my folders to this standard I also ran the troubleshooter and these folders/files still showed up even though they didn't exist on my google drive.

**Comment by Admin9705** [comment]
Did you do a reboot and did you configure plexdrive?  PlexDrive is the source of the other documents.

**Comment by AugusDogus** [comment]
I have done a reboot before, but I will do an additional one now. PlexDrive is also working.

**Comment by Admin9705** [comment]
Also run the latest update, tshoot, 2 and preinstall update and reboot.
Many fixes to unionfs. Also run the rclone, soon as u get into the menu,
select q for quit.

**Comment by AugusDogus** [comment]
Hooray! In total I rebooted 3 times hah. Thanks @Admin9705, please view this issue as closed.
