### ISSUE TITLE
Sonarr says /unionfs/tv/ does not exist

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#81]
<h3>Having some issues..</h3>
<p>While I can see my files if I use the unionfs troubleshooter and if I navigate manually to `/mnt/unionfs/tv` I can see my files, but sonarr unfortunately does not.</p>
<img src="https://image.prntscr.com/image/gUZVY4rKRIS8GqV38Ais2w.png">
<img src="https://image.prntscr.com/image/6FpYcJRsRtueQrIUYKGNzg.png">

**Comment by AugusDogus** [comment]
An important note is that this issue does not happen with Radarr.

**Comment by daveftw84** [comment]
restart the container

**Comment by Admin9705** [comment]
@daveftw84 , your becoming quite the expert.  He's correct, reboot the container using portainer (port 9000)

**Comment by AugusDogus** [comment]
I navigated to `hostname:9000` and was presented with this screen. 
<img src="https://image.prntscr.com/image/r4Gbn4ZkSB_y2520xAHeAw.png">
Upon creating my account, I was presented with a screen to chose between managing locally or remotely. I chose locally.
<img src="https://image.prntscr.com/image/PwkXppgSRfyKGsTF3Oq2OA.png">
I then chose containers on the left sidebar.
<img src="https://image.prntscr.com/image/TXqw82B0TiO_R6Qm0ZGMKg.png">
Selected the Sonarr container and clicked restart.
<img src="https://image.prntscr.com/image/pjDU5seBSEuOt9a-p4x0PA.png">
I was shown a success notification that the container had been restarted.
<img src="https://image.prntscr.com/image/udvia5vVRRmyZZXUjfgFgg.png">
After the restart was complete I navigated to Sonarr and tried to import my files. The restart did the trick and I am now able to move ahead.
<img src="https://image.prntscr.com/image/-_kZGSwzS__yEWn9xxj47A.png">
Thanks @daveftw84 and @Admin9705. I would not have known how to restart the container or that I even needed to restart the container without either of you. [Here's another good source](https://www.techrepublic.com/article/how-to-install-and-use-portainer-for-easy-docker-container-management/).

I wanted to document my steps as clearly as possible, hence the seemingly overwhelming amount of pictures, for anyone else that might encounter this problem in the future. Please view this issue as closed.
