### ISSUE TITLE
Can't create custom containers

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#815]
**Describe the bug**
The file `/opt/mycontainers/_template.yml ` is missing. Thus the instructions at `https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/wiki/Custom-Containers` no longer are accurate
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 8.15
  * Plexguide Server Type: Remote VPS
  * Plexguide Edition: Gdrive
  * Using Traefik: Yes
  * Domain DNS Provider: NameCheap

**Comment by Admin9705** [comment]
got it will check into it :D shouldn't have changed but you never know :D

**Comment by robertbaker** [comment]
The template was old. Just copy any app yml that it's similar in functionally and make edits.

**Comment by joshs85** [comment]
> The template was old. Just copy any app yml that it's similar in functionally and make edits.

This doesn't work either.  Never shows up in list of apps.

**Comment by azerial** [comment]
> 
> 
> The template was old. Just copy any app yml that it's similar in functionally and make edits.

@robertbaker I have the _template.yml and my custom container doesn't show up in the list (I of course created a new yml file that is named the image, etc, etc as per the wiki). 

Im trying to deploy a MariaDB container. Looks like this is related to the attached pull request: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/pull/824

**Comment by Admin9705** [comment]
fixed lastest update

**Comment by azerial** [comment]
**Fix Fail**

plexguide Version: 8.3.15

**Impact**: Custom containers cannot be deployed

Repro: 
1. Create a custom container using the following command `cp /opt/mycontainers/_template.yml /opt/mycontainers/containerTest.yml `
2. Modify the yaml file using nano (or just leave it the same, this is just a test).
3. Verify the yaml file is valid using nano (or less)
4. Run plexguide `sudo plexguide`
5. Select the options `4, 2, 1` ( PG Box  : Apps ~ Core, Community & Removal>PG Box: Community>Utilize Community Box - PlexGuide's)
6. Type in the name of your custom container, in this instance `containerTest` and press enter
7. Observe containerTest is listed as Apps queued for Installation
8. Type `deploy` and hit enter
9. Observe the container cannot be deployed with the error `ERROR -- No APP Queued for Install!`

**Additional Info: 
Console Output:**
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🚀 PGBox ~ Multi-App Installer           📓 Reference: pgbox.plexguide.com
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📂 Potential Apps to Install

airsonic alltube bazarr beets bitwarden booksonic bookstack
cadvisor cloudcmd containerTest ddclient deezloaderremix delugevpn deluge
duplicati embystats filebot gazee handbrake2 handbrake headphones
heimdall home-assistant htpcmanager jdownloader2 kitana logarr makemkv
mariadb mcmyadmin medusa mellow mkvtoolnix monitorr muximux
mylar nextcloud nowshowing organizr pyload radarr4k radarrhdr
resilio sharesite sonarr4k sonarrhdr speedtest synclounge syncthing
thelounge ubooquity xteve

💾 Apps Queued for Installation

containerTest

💬 Quitting? TYPE > exit | 💪 Ready to install? TYPE > deploy
🌍 Type APP for QUEUE | Press [ENTER]: deploy
ERROR -- No APP Queued for Install!
