### ISSUE TITLE
just lost control of server

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#82]
cant get into portianr, logged in with putty and was able to type plexguide but when required to enter sudo password , it kept saying access denied. now putty cant connect at all and nothing is working.
i requested a reboot and going to see whats up

**Comment by daveftw84** [comment]
so server comes back online. nothing working, i force reinstall of all containers. had to reinstall plexdrive
again. reboot server with sudo reboot.
server back online, portainer back working. 
cant access plex, server cant be found even using direct ip of server and :32400/web/index.html
plex loads up but not my server 
![image](https://user-images.githubusercontent.com/20739467/33587548-6d886f64-d923-11e7-9a83-ccbf9dae14d6.png)

**Comment by daveftw84** [comment]
![image](https://user-images.githubusercontent.com/20739467/33587565-7f806776-d923-11e7-92db-89ebf9c61582.png)

**Comment by daveftw84** [comment]
![image](https://user-images.githubusercontent.com/20739467/33587584-97afae06-d923-11e7-819f-96281ee06469.png)

**Comment by daveftw84** [comment]
had to set up a tunnel and reclaim the server. everything is gone. scanning in library all over again

**Comment by daveftw84** [comment]
is there a back up somewhere on server or something?

**Comment by daveftw84** [comment]
i now have two plex directories
/opt/plex/database/Library/Application Support/Plex Media Server/Plug-ins
/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins

**Comment by Admin9705** [comment]
Dave, must of been the move.  I apologize and forgot to make a part where it move plex to appdata.  I was setting up test for the plex backup and realized it was not in the appdata folder.  I'll ensure to have this set incase anyone upgrades.  The backup function works now with plex being in the correct spot.

**Comment by daveftw84** [comment]
my server keeps going on and off line.

**Comment by daveftw84** [comment]
my server is soooooooo unstable now. its still scanning in tv shows, which i hope is the error
but its going down like every 10 mins

**Comment by daveftw84** [comment]
@Admin9705  help please

**Comment by daveftw84** [comment]
no videos are playing, everything is buffering then cuts off

**Comment by daveftw84** [comment]
@Admin9705 
youre not going to believe this... so i reach out to wholesale interenets support and askfor hard drive testing and networking testing. they ask for my log in and then tell me it looks like my gb port is set to 100mb only..... she flips it back to a gb and now server is acting like it should, i ask how did this happen and they tell me they dont know. i ask for speed test after and they give me this results 
500 down and 790 up
so i start begging for more upload lol and they send me an other test  and tell me its where its suppose to be

Testing download speed................................................................................
Download: 586.10 Mbit/s
Testing upload speed................................................................................................
Upload: 794.98 Mbit/s

**Comment by Admin9705** [comment]
Haha really, I never have issues.  That is funny.  Ya, my speed test is
good to go.

**Comment by Admin9705** [comment]
Sorry, I only see these messages through my email because they are closed.
I'll look into it.
