### ISSUE TITLE
Ask before restarting upon uninstall

### ISSUE THREAD

**Issue by sixshooterz** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#823]
**Is your feature request related to a problem? Please describe.**
The app doesn't ask if the user wants to restart, it just does so without warning.

**Describe the feature/solution you'd like**
Prompt to reboot now or later so that other apps (Yes, we run other stuff on these boxes besides PG) can be gracefully shutdown.

**Comment by Admin9705** [comment]
remember, plexguide is designed for a clean box. for now will be left as is until the uninstaller is rewritten (low on priority list). thanks for the info though.
