### ISSUE TITLE
Emby - Help

### ISSUE THREAD

**Issue by breezytm** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#83]
A little help here

I am not sure why I can't get Emby to see subfolders within my google drive. I am guessing it must be a permission issue since clearly you have it working, reading your wiki, bu in my setup when the mount folder was created it used the chmod -R 0777 /mnt/plexdrive4, That means everyone has right. The folder works fine with Plex, Sonarr, Radarr except Emby. I even went and give the user emby:emby full permission to the folder but that didn't seem to solve the problem. See screenshot. 

![image](https://user-images.githubusercontent.com/3412923/33625366-530ed9e6-d9c5-11e7-94a8-8eaf6e9ccd76.png)

**Comment by breezytm** [comment]
Okay. I don't know if the issue is on my end but I was not able to configure Emby using the plexdrive4 mount but I was able to download plexdrive 5 and mount it. That seems to work fine. I also did not have any issues browsing the folder using the gdrive mount as well.

**Comment by Admin9705** [comment]
have you tried rebooting the emby container?

**Comment by Admin9705** [comment]
In regards to controls, we are working to finish to stablize version 4.
Once that's done, we will setup version 5 where you create a user and it's
more locked down to that user.  Grasping the nginx, docker, and other
issues all at once is tough :D

**Comment by Admin9705** [comment]
@breezytm closing unless you have an update, v5 will be out shortly

**Comment by breezytm** [comment]
Sorry. I was away on vacation. Just got back but yeah Plexdrive 5 seems to be working. Occasionally disconnects. Obviously that's a known issues. 

I am not using the docker applications as I had already install all my applications before I came across this script. I only used it to create my drive mounts which was puzzling to me. Great tutorial great app. Keep up the good work.
