### ISSUE TITLE
I suggestion for a full nano on [6] Tools option.

### ISSUE THREAD

**Issue by ruCyberPoison** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#831]
Hello devs, 

Maybe you have seen my merge pull request about the pgclonef fork, so now i trying to do a 
nano of _/opt/appdata/plexguide/rclone.conf_ for who want by a easy way to edit their rclone config looks like this is the rclone.conf the pgclone use right ? 

So is just to make as a 
nano or the best way the devs have in mind to edit it easely and import rclone.conf from existing users have used rclone before.I think i have talked about this features but now is more easy because i have perfomed some searches in the folders. sadly in the gdsaxx i need to add the path encrypted like 

[gdsaXXC]
type = crypt
remote = gdsa06:/ywqw0uKjeKY5tLahSYU/ywqw0uKjeKY5tLahSYU/
filename_encryption = standard
directory_name_encryption = true
password =  **ENCRYPTED**
password2 =  **ENCRYPTED**

To perfom my moves and i need many times to edit it again and again, pgblitz saves me so many times so i just recommend that features to be more powerful, than it's already is. 

Rgds,

**Note:** please test my pull request before implementing that changes.
It create the folder so it check and after (AT) normally rclone rmdir removes the dir...
Just test it 😉

**Comment by robertbaker** [comment]
I'm not sure what you are asking or trying to do.

Is there some environment specific configuration you're trying to do? Can you be a bit more specific and let's see if there's a different approach.

**Comment by Admin9705** [comment]
closing, i get the idea, but not ideal for space limitations :D

**Comment by robertbaker** [comment]
I think I addressed what he wanted with ngdrive, ntdrive, etc, npgblitz
