### ISSUE TITLE
Nzbget cleaning script not working

### ISSUE THREAD

**Issue by 3daystoday** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#845]
I dont know if this is a problem just me are having, beacuse I cant see any actual problem why it wouldent work in the accual script. In my /mnt/downloads/nzbget/movies i get lots of junk files that are included in the nzb.

This is running every hour but dont accualy remove anything:
bash /opt/plexguide/menu/roles/autodelete/scripts/nzbget.sh
-
#!/bin/bash
find /mnt/downloads/nzbget/tv/* -maxdepth 1 -mmin +240 -type f -exec rm -fv {} 2>/dev/null \;
find /mnt/downloads/nzbget/music/* -maxdepth 1 -mmin +240 -type f -exec rm -fv {} 2>/dev/null \;
find /mnt/downloads/nzbget/movies/* -maxdepth 1 -mmin +240 -type f -exec rm -rfv {} 2>/dev/null \;
find /mnt/downloads/nzbget/ebooks/* -maxdepth 1 -mmin +240 -type f -exec rm -fv {} 2>/dev/null \;
find /mnt/downloads/nzbget/abooks/* -maxdepth 1 -mmin +240 -type f -exec rm -fv {} 2>/dev/null \;

**Comment by Admin9705** [comment]
ok good check, will patch

**Comment by robertbaker** [comment]
Redeploy nzbget to fix

**Comment by robertbaker** [comment]
Redeploy your mounts. Those scripts are no longer used and will be removed in the next pgupdate.

Empty directories at least 5m old are now deleted.D
Directories under downloads that are less than 100mb and at least an 360m old will be removed.

This should solve the issue.
