### ISSUE TITLE
Strange menu behaviour

### ISSUE THREAD

**Issue by stephenc87** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#850]
If I tried to leave some of the menu's (for example the pgpress menu) with the Z key, I will just end up in a faulty selection of that item

**Comment by robertbaker** [comment]
This is valid. This happens if you exit on the screen where you pick PlexGuide or your Fork.

See if you can fix this one :)

**Comment by Admin9705** [comment]
i'm tracking the issue @robertbaker and no one has mentioned it yet. when they exit from it but not pick either one, it will go to the fork; if never has been replicated, can go bonkers.

**Comment by stephenc87** [comment]
I tried bringing it up earlier but you banned me!!! I'm happy to fix it but
you need to trust me, I've got more then enough experience for this project
but I need to communicate if you want my help
