### ISSUE TITLE
move script error

### ISSUE THREAD

**Issue by batedk** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#86]
for rclone-en.sh & rclone-un.sh

`rclone move --bwlimit 9M --tpslimit 4 --max-size 99G --log-level INFO --stats 15s local:/mnt/move gdrive:/`

delete `local:`

**Comment by Admin9705** [comment]
ok i'll try this on my real server.

**Comment by Admin9705** [comment]
rclone move source:path dest:path [flags]

**Comment by Admin9705** [comment]
@batedk fixed, thanks bud
