### ISSUE TITLE
Traefik Not Working 

### ISSUE THREAD

**Issue by sharkeydavid** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#862]
Hi, Updated to 8.4.18 and reverse proxy stopped working.

Started new machine with 8.4.18 and new domain to test - Didn't work.
Started new machine with 8.4.15 with (another) new domain - Worked.

I have the machine's still running if you want any more details for the ticket.

**Comment by Admin9705** [comment]
There's no changes in traefik from 8.4.18 from 8.4.15; when it does the pull; it pulled the exact same thing.  Traefik has been rewritten in 8.5; so no need to chase rabbits :D but thanks for the report.

**Comment by sharkeydavid** [comment]
Fair point Mr Admin. I will try to make any reports a bit more wholesome by reading the changelogs in the future, I see now that note on Traefik
