### ISSUE TITLE
chown: invalid user: ‘plexguide:1000’

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#88]
-- Fresh install of ubuntu 16.04
-- Ran `apt-get install && apt-get upgrade`
-- Ran the commands to install plexguide
-- Started plexguide with the command `plexguide`
-- Recieved the error`chown: invalid user: ‘plexguide:1000’`

Plexguide does not exit as step 2 of the guide says.
When attemping to `su plexguide` after exiting manually, I recieve the error `No passwd entry for user 'plexguide'`.

**Comment by Admin9705** [comment]
Goto t-shoot. It reruns it again.  I need to fix the wording; u can execute without being plexguide. It just helps incase.

**Comment by AugusDogus** [comment]
I ran plexguide, forced the preinstall, updated. Then I ran plexguide again, and selected `User: plexguide` and ran the update again. 

This issue persists with no changes.

**Comment by Admin9705** [comment]
What type of server do you have? Personal or with some else including if a vps and etc?

**Comment by Admin9705** [comment]
To force beginning again, delete the file in /var/plexguide/

**Comment by AugusDogus** [comment]
It's a VPS through ssdnodes, I pay for it yearly. 

Both times I tried installing plexguide mentioned in this thread were on clean installs of Ubuntu 16.04 with the native kernel. 

I ran apt-get install and apt-get upgrade on both.

Users should be default.

**Comment by AugusDogus** [comment]
After updating, forcing a preinstall and selecting the option to force recreate the user I was successfully able to `su plexguide`, but I was unable to start plexguide as it prompted me for my password and it never before prompted me to create a password for the account. I then manually ran `sudo passwd plexguide` from the root account and entered my password here. After this I was able to `su plexguide` once more and start plexguide.

**Comment by Admin9705** [comment]
@AugusDogus plexguide:1000 dependency is gone

**Comment by daveftw84** [comment]
that ssdnodes sever isnt going to be enough. trust me 
had one my self

**Comment by daveftw84** [comment]
this system takes alot of ram to run, i have 64 gb and still run out. free space is also important, when converting videos it needs space to do the converting.
then lets not forget free space needed to download videos then transfer over to drive.
only way you can get away with this is, if very one only uses direct play. plus maybe 2 vps servers, one for downloads other for plex
