### ISSUE TITLE
Error importing in Sonarr

### ISSUE THREAD

**Issue by amendolaro** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#92]
NZBget downloads fine, and sonarr tries to move the file and it fails. logs show:

Import failed, path does not exist or is not accessible by Sonarr: /downloads/completed/X.Y.Z
(XYZ being the show)

Plexguide user is still on system but i am signed in as my user

running VM ware, fresh install of ubuntu-16.04.3-desktop-amd64

***** weird thing is that SABnzb works perfectly fine.****

**Comment by Admin9705** [comment]
I had SAB working on my end.  I'm going to rework how NZBGET works.  I haven't had time to fix it it, but all the permission issues are gone.  I put plexguide user there to create a 1000:1000 permission group.  All the permissions are now 1000:1000 and back to mnt.  Give me a minute on NZBGET.   NZBGET is just a pain with all the directories that it creates.

**Comment by Admin9705** [comment]
@amendolaro can you do me a favor, can you do a ls -la check on /mnt/nzbget/completed and tell me who owns it and permissions?

**Comment by Admin9705** [comment]
@amendolaro i'm think i know what the problem is.  Did you ever set the CATEGORIES tv and movies including their paths? If it's pulling a show, it should /completed/tv -- did you check all your paths?

https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/wiki/NZBGET

**Comment by Admin9705** [comment]
@amendolaro all worked on my end. incase your ever wondering, use portainer - port 9000.  select the console and hit submit. type dir and you'll notice the folders there. I was able to see everything, so that's a good sign.  Shows downloaded from nzb and sab moved, renamed and was uploaded.

**Comment by amendolaro** [comment]
Reading is fundamental. I failed to read the set up of NZB get with the paths. So I’m sure that’s the issue. I did follow the instructions for SABnzb And that would explain why it works LOL. You can close this. Thank you for being so prompt

**Comment by Admin9705** [comment]
It's all good. There were major changes with all these permissions, but it
helps me double check myself.  If you love the program, let other know and
feedback is always great!
