### ISSUE TITLE
System breaking updates

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#93]
While I love that this repo is so active and it gets the updates that it does, I can't help but feel like I'm on the bleeding edge.

This suite of scripts is intended to make it simple to install plex, but 'simpleness' comes in two parts. Ease of use and time spent. While the ease of use has been greatly reduced, the time spent on trying to make this thing work less than half the time really starts to ramp up.

It would be fantastic to see in the near future tests that help to validate everything is working before merging to the master branch for general population. It seems like 9 out of the 10 times an issue happens it's just some behind the scenes problem that gets fixed in the next update or a few down the line. We don't really get to hear about it. 

Occasionally these updates come within mere seconds of a previous update and it's hard to know if you're even up to date at all.

While I'm in favor of the new method using the user plexguide I personally already had to scrap my previous install of plex because of some other issues with plexguide that magically got fixed with this version.

I understand this is a learning process, but tests are needed incredibly badly. End to end and unit tests. However that may be accomplished.

Gripe over, thanks again for working on this project. I hope it can help me more in the future.

**Comment by Admin9705** [comment]
@AugusDogus try a fresh install. it was reported by another user it works perfect as i test it also. it really came down to permissions causing chaos.  the goal was to eliminate root from running everything. now, everything runs as 1000:1000 for permissions and back to /mnt/  In reality, the program has been in development mode, but  I learned alot from the permission issues.  The permissions result in folders being locked, files not being able to move.  So try it out again :D

**Comment by daveftw84** [comment]
stuff is moving on my server but my local drive is still getting full.
 i have 110 gb left from a tb hard drive
![image](https://user-images.githubusercontent.com/20739467/34226004-2900ad96-e57d-11e7-9bd9-d75eeccdc680.png)
![image](https://user-images.githubusercontent.com/20739467/34226019-3a1f2c1a-e57d-11e7-90fe-10803db40860.png)
