### ISSUE TITLE
rm: cannot remove 'dep*': No such file or directory

### ISSUE THREAD

**Issue by AugusDogus** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#95]
When running the preinstall, after all the steps have been completed, right before it moves onto the UI text appears saying `Press any key to continuerm: cannot remove 'dep*': No such file or directory`.

**Comment by Admin9705** [comment]
added to a dev/nulls to a few items, should affect the program.  Good report @AugusDogus. Let me know if it ever comes up
