### ISSUE TITLE
local drive now full un-sync not moving files

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#96]
do i have to reboot server?

**Comment by daveftw84** [comment]
reboot server didnt help, rebuilt contairs and now sabnd wont load up.
 "/config/sabnzbd.ini" is not a valid configuration file<br>Error message: [Errno 13] Permission denied: '/config/sabnzbd.ini'
Specify a correct file or delete this file.

**Comment by daveftw84** [comment]
looks like i have to rebuild the whole server? doing a back up now of the plex database. last time it looks like it froze at uploading files to drive.

**Comment by daveftw84** [comment]
been over 2 hours stuck on "copy files to google drive"  while doing a back up of the plex.

**Comment by daveftw84** [comment]
![image](https://user-images.githubusercontent.com/20739467/34241011-2849f50c-e5c7-11e7-8438-cc3eae20f881.png)

**Comment by Admin9705** [comment]
ya takes forever to copy, but works! what is the issue you are having?

**Comment by Admin9705** [comment]
@daveftw84 how are things looking?

**Comment by daveftw84** [comment]
I believe it copied over I just let it sit overnight and I forgot all about
it to be honest

**Comment by daveftw84** [comment]
I'm still losing file space  on the local Drive even with the downloader
cap at 8mb per second

**Comment by Admin9705** [comment]
But what is eating at your space? You could have left over files from
sabnzbd or nzbget taking space.

**Comment by daveftw84** [comment]
It's pretty much files that refused to copy over

**Comment by daveftw84** [comment]
even have unpacked labels on some

**Comment by daveftw84** [comment]
Merry Christmas

On Dec 25, 2017 11:29 AM, "Chum lee" <daveftw84@gmail.com> wrote:

even have unpacked labels on some

**Comment by daveftw84** [comment]
Did a Plex guide update now I can't get into Portner

**Comment by Admin9705** [comment]
Use programs > critical> portainer
