### ISSUE TITLE
permisions 

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#97]
im trying to run sudo chown -Rv plex.plex "$(sudo find / -mount -type d -name Plug-ins)"
but it tells me user is invailed
i tried runing sudo chown -Rv plexguide.plexguide "$(sudo find / -mount -type d -name Plug-ins)"
and it told me the same thing
but thats the user i been logging in as 
so i tried the recreate user and set password.
and ran update, nothing seems to change never get to set a password.
try running recreate user again and tellls me /var/plexguide/user dont exist
so i try running as root and get the same thing.
i see your tutorial never says to create an user name plexguide, so i was wondering... am i suppose to have a sudo user name plexguide?

**Comment by Admin9705** [comment]
ya the plugins, some put there and i havne't tested.  For the future, you don't need plexguide anymore.  If you were using the older version of 5, lets say 4-5 days prior to that, there had been major changes. are things working ok for you? drop by our deluge channel for faster responses.

**Comment by daveftw84** [comment]
Yeah I pretty much reinstalled the server to get everything functioning
correctly.
Had to wipe the conflict folders that gave me permission issues

**Comment by Admin9705** [comment]
So is this good for closure? Did it work out for you?

**Comment by daveftw84** [comment]
Ya

On Dec 22, 2017 10:00 PM, "Admin9705" <notifications@github.com> wrote:

So is this good for closure? Did it work out for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/issues/97#issuecomment-353709231>,
or mute the thread

**Comment by Admin9705** [comment]
@daveftw84 thanks!
